// GENERATED by scripts/generate-figma.ts — DO NOT EDIT.
// Source of truth: contracts/devis.contract.json (ds.devis v1.2.0)
// Amend-capable (#60): an existing component (set) carrying our identity
// marker is reconciled IN PLACE (same node id + key); unchanged specs skip.
const COMPONENTS = [
  {
    "setName": "Devis",
    "contractId": "ds.devis",
    "anchorKey": "0caac7487988d0da129211e64a40545163149a6f",
    "description": "Devis — generated from contract ds.devis v1.2.0 · image frame: runtime slot, photo shown is a mockup sample †",
    "isSet": false,
    "boolProps": [],
    "textProps": [],
    "forwardedProps": [],
    "swapProps": [],
    "fontStyles": [
      "Medium",
      "Regular"
    ],
    "variants": [
      {
        "name": "Devis",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Devis",
          "layout": {
            "mode": "VERTICAL",
            "primary": "MIN",
            "counter": "CENTER"
          },
          "fill": "color/noir-pur",
          "bindings": {
            "paddingTop": "space/96",
            "paddingBottom": "space/96"
          },
          "fixedWidth": {
            "px": 1728,
            "varName": "size/devis/root"
          },
          "children": [
            {
              "type": "frame",
              "name": "Background",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "MIN",
                "counter": "MIN"
              },
              "insetOverlay": true,
              "imgPlaceholder": true,
              "lits": {
                "fillColor": {
                  "r": 0.8509803921568627,
                  "g": 0.8509803921568627,
                  "b": 0.8509803921568627
                },
                "width": 1728
              },
              "children": [],
              "visibleDefault": true
            },
            {
              "type": "frame",
              "name": "Voile",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "MIN",
                "counter": "MIN"
              },
              "insetOverlay": true,
              "lits": {
                "fillColor": {
                  "r": 0,
                  "g": 0,
                  "b": 0,
                  "a": 0.30196078431372547
                },
                "width": 1728
              },
              "children": [],
              "visibleDefault": true
            },
            {
              "type": "frame",
              "name": "Container",
              "layout": {
                "mode": "VERTICAL",
                "primary": "MIN",
                "counter": "CENTER"
              },
              "bindings": {
                "itemSpacing": "space/32"
              },
              "children": [
                {
                  "type": "text",
                  "name": "Titre",
                  "fixedWidth": {
                    "px": 900,
                    "varName": "size/devis/titre"
                  },
                  "characters": "Prenez rendez-vous pour un devis gratuit, nous nous déplaçons chez vous",
                  "fontSize": 40,
                  "fontStyle": "Regular",
                  "textStyle": "Titre 2",
                  "textFill": "color/blanc",
                  "lineHeight": 50,
                  "textAlignH": "CENTER",
                  "fontFamily": "Montserrat",
                  "contentProp": "Titre"
                },
                {
                  "type":"instance",
                  "name": "Bouton",
                  "dep":"Button",
                  "depId": "ds.button",
                  "depProps": {
                    "Libelle": "Prendre rendez-vous",
                    "Style": "Outline blanc",
                    "Icone droite": true
                  }
                }
              ]
            }
          ]
        }
      }
    ],
    "colW": 1788
  }
];
const ROW_H = 240, PAD = 40;

// 017 — le registre gouverné des levées du refus photo (FR-003a/FR-003b),
// baké ici parce que le bac à sable Figma ne lit aucun fichier et que core/
// n'en lit pas non plus (§VII). Vide = le refus ne se lève sur rien, ce qui
// est l'état normal : une entrée est une décision owner avec son reçu.
const ACQUITTEMENTS_PHOTOS = [];

const EXPECTED_FILE_KEY = "d9FYAUcqdcNtsuaMgLefvJ";
if (EXPECTED_FILE_KEY && figma.fileKey && figma.fileKey !== EXPECTED_FILE_KEY) {
  throw new Error('WRONG FILE: expected ' + EXPECTED_FILE_KEY + ', got ' + figma.fileKey);
}

await figma.loadAllPagesAsync();

const allVars = await figma.variables.getLocalVariablesAsync();
const varByName = {};
for (const v of allVars) varByName[v.name] = v;
const need = (name) => {
  const v = varByName[name];
  if (!v) throw new Error('Missing variable: ' + name);
  return v;
};
const boundPaint = (varName, consumer) => {
  // Seed the base with the resolved value when a consumer node is known:
  // Figma keeps rendering a reassigned bound paint's BASE color on
  // pre-existing nodes (fresh nodes normalize at assignment) — without the
  // seed, amended variants render black. The binding itself is unchanged.
  // B-3 finding 2: the resolved ALPHA rides the seed too (paint opacity) —
  // discarding it rendered Badge's rgba(0,0,0,.06) pill as opaque black on
  // amended nodes.
  const v = need(varName);
  let base = { r: 0, g: 0, b: 0 };
  let alpha = 1;
  if (consumer) {
    try {
      const r = v.resolveForConsumer(consumer);
      if (r && r.value && r.value.r !== undefined) {
        base = { r: r.value.r, g: r.value.g, b: r.value.b };
        if (typeof r.value.a === 'number') alpha = r.value.a;
      }
    } catch (e) { /* fall back to black base */ }
  }
  return figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: base, opacity: alpha }, 'color', v);
};

// Named text styles (synced by 01-tokens.js): consumers look up OUR styles
// only — the ds_contracts/textStyleToken marker is identity, a foreign style
// sharing a name is never used. A governed plain-text node must not silently
// fall back to raw typography: missing or duplicate marked styles STOP.
let _textStyleMap = null;
async function ourTextStyle(name) {
  if (!_textStyleMap) {
    _textStyleMap = {};
    for (const s of await figma.getLocalTextStylesAsync()) {
      if (!s.getSharedPluginData('ds_contracts', 'textStyleToken')) continue;
      if (_textStyleMap[s.name]) throw new Error('Duplicate governed Text Style name: ' + s.name);
      _textStyleMap[s.name] = s;
    }
  }
  return _textStyleMap[name] || null;
}

// FONTES — résolution par famille ET orthographe de style.
//
// Le défaut que ceci répare (016, lot R-pilote-tab, trouvé sur le canvas réel) :
// la table des poids épelle les styles à la façon d'Inter ('Semi Bold', avec une
// espace) ; la plupart des familles — Montserrat comprise — les épellent compact
// ('SemiBold'). Le runtime posait Inter en dur puis tentait un rattrapage avec
// l'orthographe d'Inter appliquée à Montserrat : loadFontAsync refusait la paire,
// un catch avalait l'erreur EN SILENCE, et tout le texte régénéré restait en Inter.
// Mesuré sur le fichier client : "fontPostScriptName": "Montserrat-SemiBold".
//
// On essaie donc les deux orthographes, dans l'ordre, et surtout : on NOMME le
// repli quand il a lieu (fontFallbacks), au lieu de dégrader sans le dire.
const FONT_STYLE_ALIASES = { 'Semi Bold': ['Semi Bold', 'SemiBold'], 'Extra Light': ['Extra Light', 'ExtraLight'], 'Extra Bold': ['Extra Bold', 'ExtraBold'] };
const fontFallbacks = [];
const _fontCache = {};
async function resolveFont(family, style) {
  const k = family + '|' + style;
  if (k in _fontCache) return _fontCache[k];
  const candidates = FONT_STYLE_ALIASES[style] || [style];
  for (const candidate of candidates) {
    try {
      await figma.loadFontAsync({ family: family, style: candidate });
      return (_fontCache[k] = { family: family, style: candidate });
    } catch (e) { /* orthographe suivante */ }
  }
  return (_fontCache[k] = null);
}
async function textFont(spec) {
  const style = (spec && spec.fontStyle) || 'Medium';
  const family = (spec && spec.fontFamily) || 'Inter';
  const wanted = await resolveFont(family, style);
  if (wanted) return wanted;
  const used = (await resolveFont('Inter', style)) || (await resolveFont('Inter', 'Regular')) || { family: 'Inter', style: 'Regular' };
  fontFallbacks.push({ wanted: family + ' ' + style, used: used.family + ' ' + used.style });
  return used;
}

function basePropertyName(key) { return String(key || '').split('#')[0]; }
async function applyRichTextRanges(node, ranges) {
  if (!ranges || ranges.length === 0) return;
  if (!node || node.type !== 'TEXT') throw new Error('Rich-text target is not a TEXT node');
  const length = node.characters.length;
  for (const range of ranges) {
    if (range.start < 0 || range.end <= range.start || range.end > length) {
      throw new Error('Invalid rich-text range ' + range.start + '..' + range.end + ' for TEXT length ' + length);
    }
    const current = node.getRangeFontName(range.start, Math.min(range.end, range.start + 1));
    const family = current && typeof current === 'object' && current.family
      ? current.family
      : (node.fontName && typeof node.fontName === 'object' && node.fontName.family ? node.fontName.family : 'Inter');
    const wanted = await resolveFont(family, range.fontStyle);
    if (!wanted) throw new Error('Cannot load rich-text font: ' + family + ' ' + range.fontStyle);
    node.setRangeFontName(range.start, range.end, wanted);
  }
}
function textNodeForInstanceProperty(instance, property) {
  const candidates = typeof instance.findAll === 'function'
    ? instance.findAll((n) => n.type === 'TEXT' && n.componentPropertyReferences && n.componentPropertyReferences.characters)
    : [];
  return candidates.find((n) => basePropertyName(n.componentPropertyReferences.characters) === property) || null;
}
async function applyDepRichTextRanges(instance, entries) {
  for (const entry of entries || []) {
    const text = textNodeForInstanceProperty(instance, entry.property);
    if (!text) throw new Error('Rich-text child property has no rendered TEXT target: ' + entry.property);
    await applyRichTextRanges(text, entry.ranges);
  }
}

function propertyValueByBase(node, base) {
  if (node && node.type === 'INSTANCE') {
    const key = Object.keys(node.componentProperties || {}).find((k) => basePropertyName(k) === base);
    return key ? node.componentProperties[key].value : undefined;
  }
  if (node && (node.type === 'COMPONENT' || node.type === 'COMPONENT_SET')) {
    const key = Object.keys(node.componentPropertyDefinitions || {}).find((k) => basePropertyName(k) === base);
    return key ? node.componentPropertyDefinitions[key].defaultValue : undefined;
  }
  return undefined;
}
function fontRanges(node) {
  if (!node || node.type !== 'TEXT') return [];
  if (typeof node.getStyledTextSegments !== 'function') {
    const f = node.fontName;
    return f && typeof f === 'object' && f.family
      ? [{ start: 0, end: node.characters.length, fontName: { family: f.family, style: f.style } }]
      : [];
  }
  return node.getStyledTextSegments(['fontName']).map((s) => ({
    start: s.start, end: s.end,
    fontName: s.fontName && typeof s.fontName === 'object' && s.fontName.family
      ? { family: s.fontName.family, style: s.fontName.style }
      : null,
  }));
}
function sameValue(a, b) { return JSON.stringify(a) === JSON.stringify(b); }
function preparerSauvetageConsommateurs(master, info) {
  const hotes = [];
  for (const h of info.hotes || []) {
    if (h.role !== 'instance') continue;
    const props = [], textes = [], espacements = [];
    // Cursor queue (same FIFO order as shift, without the O(n) pops); the
    // master reference rides each entry so the parallel descent replaces a
    // per-node noeudAuChemin walk from the root. A missing reference at any
    // depth still surfaces as the same named refusal when its entry is read.
    const pile = [{ n: h.node, ref: master, c: '' }];
    let cursor = 0;
    while (cursor < pile.length) {
      const item = pile[cursor++];
      const n = item.n;
      const ref = item.ref;
      if (!ref) throw new Error('REFUS consommateurs — chemin absent du master avant mutation: hostId=' + h.hostId + ' chemin=' + item.c);
      if (n.type === 'INSTANCE') {
        const signature = Object.keys(n.componentProperties || {}).map(basePropertyName).sort();
        for (const key of Object.keys(n.componentProperties || {})) {
          const base = basePropertyName(key);
          const value = n.componentProperties[key].value;
          if (!sameValue(value, propertyValueByBase(ref, base))) props.push({ chemin: item.c, property: base, value: value, signature: signature });
        }
      }
      if (n.type === 'TEXT') {
        const ranges = fontRanges(n);
        const refRanges = fontRanges(ref);
        if (n.characters !== ref.characters || !sameValue(ranges, refRanges)) {
          const property = n.componentPropertyReferences && n.componentPropertyReferences.characters
            ? basePropertyName(n.componentPropertyReferences.characters)
            : null;
          textes.push({ chemin: item.c, property: property, characters: n.characters, ranges: ranges });
        }
      }
      if (typeof n.itemSpacing === 'number' && typeof ref.itemSpacing === 'number' && n.itemSpacing !== ref.itemSpacing) {
        espacements.push({ chemin: item.c, itemSpacing: n.itemSpacing });
      }
      const kids = n.children || [];
      const refKids = ref.children || [];
      for (let i = 0; i < kids.length; i++) pile.push({ n: kids[i], ref: refKids[i], c: cheminEnfantDe(item.c, i) });
    }
    hotes.push({ hostId: h.hostId, node: h.node, props: props, textes: textes, espacements: espacements });
  }
  return { hotes: hotes };
}
async function restaurerSauvetageConsommateurs(plan, report) {
  const restored = [];
  for (const h of plan.hotes || []) {
    for (const p of h.props) {
      let node = noeudAuChemin(h.node, p.chemin);
      const carriesProperty = (n) => {
        if (!n || n.type !== 'INSTANCE') return false;
        const bases = Object.keys(n.componentProperties || {}).map(basePropertyName).sort();
        return bases.indexOf(p.property) >= 0;
      };
      if (!carriesProperty(node)) {
        let candidates = typeof h.node.findAll === 'function'
          ? h.node.findAll((n) => carriesProperty(n))
          : [];
        // The complete property signature disambiguates two composed
        // instances exposing the same property. It is a tie-breaker, not a
        // prerequisite: Figma can add/remove dependency properties between
        // the two snapshots while the governed property identity remains.
        if (candidates.length > 1 && p.signature) {
          const exact = candidates.filter((n) => sameValue(
            Object.keys(n.componentProperties || {}).map(basePropertyName).sort(),
            p.signature,
          ));
          if (exact.length > 0) candidates = exact;
        }
        if (candidates.length !== 1) {
          throw new Error('REFUS consommateurs — instance introuvable ou ambiguë après reconstruction: hostId=' + h.hostId + ' chemin=' + p.chemin + ' property=' + p.property + ' candidates=' + candidates.length);
        }
        node = candidates[0];
      }
      setInstanceProps(node, { [p.property]: p.value });
    }
    for (const e of h.espacements) {
      const node = noeudAuChemin(h.node, e.chemin);
      if (!node || typeof node.itemSpacing !== 'number') throw new Error('REFUS consommateurs — gap introuvable après reconstruction: hostId=' + h.hostId + ' chemin=' + e.chemin);
      node.itemSpacing = e.itemSpacing;
    }
    for (const t of h.textes) {
      let node = noeudAuChemin(h.node, t.chemin);
      if (
        (!node || node.type !== 'TEXT' ||
          (t.property && basePropertyName(node.componentPropertyReferences && node.componentPropertyReferences.characters) !== t.property)) &&
        t.property
      ) {
        node = (typeof h.node.findAll === 'function'
          ? h.node.findAll((n) => n.type === 'TEXT' && basePropertyName(n.componentPropertyReferences && n.componentPropertyReferences.characters) === t.property)
          : [])[0] || null;
      }
      if (!node || node.type !== 'TEXT') throw new Error('REFUS consommateurs — TEXT introuvable après reconstruction: hostId=' + h.hostId + ' chemin=' + t.chemin);
      for (const r of t.ranges) {
        if (!r.fontName) throw new Error('REFUS consommateurs — fontName mixte illisible: hostId=' + h.hostId + ' chemin=' + t.chemin);
        const loaded = await resolveFont(r.fontName.family, r.fontName.style);
        if (!loaded) throw new Error('REFUS consommateurs — police introuvable: ' + r.fontName.family + ' ' + r.fontName.style);
      }
      if (node.characters !== t.characters) node.characters = t.characters;
      for (const r of t.ranges) {
        const loaded = await resolveFont(r.fontName.family, r.fontName.style);
        node.setRangeFontName(r.start, r.end, loaded);
      }
    }
    restored.push({ hostId: h.hostId, props: h.props.length, textes: h.textes.length, espacements: h.espacements.length });
  }
  report.consumerOverrides = { verdict: 'vert', hotes: restored };
}
const fontStyles = new Set(['Medium']);
for (const C of COMPONENTS) for (const s of C.fontStyles) fontStyles.add(s);
for (const style of fontStyles) {
  await resolveFont('Inter', style);
}

// State previews (figmaStatePreviews): merge the enum-API cartesian with the
// canvas-only preview overlay; base variants gain an explicit State=Default
// segment so every variant in the set carries the axis (Figma derives
// variant properties from names). Contracts without previews pass through
// untouched — names, hashes, and amend reconciliation are unchanged.
function withStateAxis(C) {
  if (!C.stateVariants || C.stateVariants.length === 0) return C.variants;
  return C.variants.map((v) => {
    const name = v.name.indexOf('=') >= 0 ? v.name + ', State=Default' : 'State=Default';
    return Object.assign({}, v, { name: name, spec: Object.assign({}, v.spec, { name: name }) });
  }).concat(C.stateVariants);
}

function findComponentByName(name, contractId) {
  // 016: identity FIRST — the ds_contracts/contractId marker survives any layer
  // rename (the live file spells the button master « Bouton »; the contract says
  // 'Button'; §VIII: a copy's own layer name is never an identity). The name
  // lookup stays as the fallback for pre-marker files.
  if (contractId) {
    for (const page of figma.root.children) {
      const hit = page.findOne(
        (n) =>
          (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') &&
          n.getSharedPluginData('ds_contracts', 'contractId') === contractId,
      );
      if (hit) return hit;
    }
  }
  for (const page of figma.root.children) {
    const hit = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === name,
    );
    if (hit) return hit;
  }
  throw new Error('Dependency component not found in file: ' + name + ' (sync it first)');
}

// Icon identity is immutable within one execution: the same ~16 registry refs
// resolve for every icon-instance of every variant, so the id lookup and the
// full-page fallback scan run once per ref, not once per reference.
const iconComponentCache = new Map();
async function findIconComponent(ref) {
  const cacheKey = ref.nodeId + '|' + (ref.key || '');
  const cached = iconComponentCache.get(cacheKey);
  if (cached) return cached;
  let hit = typeof figma.getNodeByIdAsync === 'function' ? await figma.getNodeByIdAsync(ref.nodeId) : null;
  if (hit && hit.type !== 'COMPONENT' && hit.type !== 'COMPONENT_SET') hit = null;
  if (!hit || (ref.key && hit.key !== ref.key)) {
    hit = null;
    for (const page of figma.root.children) {
      const byKey = page.findOne(
        (n) => (n.type === 'COMPONENT' || n.type === 'COMPONENT_SET') && n.key === ref.key,
      );
      if (byKey) { hit = byKey; break; }
    }
  }
  if (!hit) {
    throw new Error('Governed icon component not found: ' + ref.asset + ' (nodeId=' + ref.nodeId + ', key=' + ref.key + ')');
  }
  const resolved = hit.type === 'COMPONENT_SET' ? hit.defaultVariant : hit;
  iconComponentCache.set(cacheKey, resolved);
  return resolved;
}

async function iconSwapDefinition(spec) {
  const defaultMain = await findIconComponent(spec.defaultComponent);
  const preferredValues = [];
  for (const ref of spec.preferredComponents || []) {
    const main = await findIconComponent(ref);
    preferredValues.push({ type: 'COMPONENT', key: main.key });
  }
  return { defaultId: defaultMain.id, preferredValues: preferredValues };
}

function wireIconSwapNodes(registry, property, key) {
  for (const entry of registry.iconSwaps || []) {
    if (entry.property !== property) continue;
    entry.instance.componentPropertyReferences = {
      ...(entry.instance.componentPropertyReferences || {}),
      mainComponent: key,
    };
  }
}

function wireDepPropForwards(registry) {
  for (const entry of registry.forwards || []) {
    const childKeys = Object.keys(entry.instance.componentProperties || {});
    for (const mapping of entry.mappings) {
      const found = childKeys.some(
        (key) => key === mapping.childProperty || key.indexOf(mapping.childProperty + '#') === 0,
      );
      if (!found) throw new Error('Child property definition not found for forwarding: ' + mapping.childProperty);
    }
    // Real Figma refuses writes to componentPropertyReferences on an
    // instance sublayer. isExposedInstance is its public, native API for
    // surfacing the nested component's own suffixed property identities at
    // the containing component instance level — one flag per instance.
    if (entry.mappings.length > 0) entry.instance.isExposedInstance = true;
  }
}

function setInstanceProps(inst, props) {
  const available = Object.keys(inst.componentProperties);
  const resolved = {};
  for (const [wanted, value] of Object.entries(props)) {
    const key = available.find((k) => k === wanted || k.startsWith(wanted + '#'));
    if (!key) continue;
    let v = value;
    // 016: an INSTANCE_SWAP property takes a COMPONENT ID — contract enums map
    // to component NAMES at compile time (CarouselControls passed "ChevronLeft"
    // and Figma refused: "Property value is incompatible with component
    // property type"). Resolve name -> id here; a name never contains ':',
    // a node id always does.
    const def = inst.componentProperties[key];
    if (def && def.type === 'INSTANCE_SWAP' && typeof v === 'string' && v.indexOf(':') < 0) {
      const target = findComponentByName(v);
      v = (target.type === 'COMPONENT_SET' ? target.defaultVariant : target).id;
    }
    resolved[key] = v;
  }
  if (Object.keys(resolved).length > 0) inst.setProperties(resolved);
}

let _slotUtil = null;
async function ensureSlotUtility() {
  if (_slotUtil) return _slotUtil;
  for (const page of figma.root.children) {
    const hit = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'Slot');
    if (hit) { _slotUtil = hit; return hit; }
  }
  // Fresh file: create it (found by the 2026-07-06 fresh-file rebuild test —
  // the lookup-only version threw in a blank file).
  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
  const util = figma.createComponent();
  util.name = 'Slot';
  util.layoutMode = 'HORIZONTAL';
  util.primaryAxisAlignItems = 'CENTER';
  util.counterAxisAlignItems = 'CENTER';
  util.paddingLeft = util.paddingRight = 12;
  util.paddingTop = util.paddingBottom = 8;
  util.cornerRadius = 4;
  util.fills = [];
  util.strokes = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.dashPattern = [4, 4];
  const t = figma.createText();
  t.fontName = { family: 'Inter', style: 'Medium' };
  t.fontSize = 12;
  t.characters = 'Slot';
  t.fills = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.appendChild(t);
  let utilPage = figma.root.children.find((p) => p.name === 'Utilities');
  if (!utilPage) { utilPage = figma.createPage(); utilPage.name = 'Utilities'; }
  utilPage.appendChild(util);
  util.x = 100; util.y = 100;
  _slotUtil = util;
  return util;
}

function applyFrameSpec(node, spec) {
  const l = spec.layout || { mode: 'HORIZONTAL', primary: 'MIN', counter: 'MIN' };
  node.layoutMode = l.mode;
  node.primaryAxisAlignItems = l.primary;
  node.counterAxisAlignItems = l.counter;
  node.primaryAxisSizingMode = 'AUTO';
  node.counterAxisSizingMode = 'AUTO';
  if (node.type === 'FRAME') node.fills = [];
  for (const [field, varName] of Object.entries(spec.bindings || {})) {
    node.setBoundVariable(field, need(varName));
  }
  if (spec.fill) node.fills = [boundPaint(spec.fill, node)];
  if (spec.stroke) {
    node.strokes = [boundPaint(spec.stroke, node)];
    node.strokeAlign = 'INSIDE';
  }
  if (spec.fixedWidth || spec.fixedHeight) {
    const w = spec.fixedWidth ? spec.fixedWidth.px : node.width;
    const h = spec.fixedHeight ? spec.fixedHeight.px : node.height;
    node.resize(w, h);
    const horizontalIsPrimary = l.mode === 'HORIZONTAL';
    if (spec.fixedWidth) {
      if (l.mode !== 'GRID') {
        if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED';
        else node.counterAxisSizingMode = 'FIXED';
      }
      node.setBoundVariable('width', need(spec.fixedWidth.varName));
    }
    if (spec.fixedHeight) {
      if (l.mode !== 'GRID') {
        if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED';
        else node.primaryAxisSizingMode = 'FIXED';
      }
      if (spec.fixedHeight.varName) node.setBoundVariable('height', need(spec.fixedHeight.varName));
    }
  }
  if (spec.lits) {
    // v14 literals: no variable to bind — plain values, compile-parsed.
    const li = spec.lits;
    if (li.paddingTop !== undefined) node.paddingTop = li.paddingTop;
    if (li.paddingBottom !== undefined) node.paddingBottom = li.paddingBottom;
    if (li.paddingLeft !== undefined) node.paddingLeft = li.paddingLeft;
    if (li.paddingRight !== undefined) node.paddingRight = li.paddingRight;
    if (li.itemSpacing !== undefined) node.itemSpacing = li.itemSpacing;
    if (li.gridColumnGap !== undefined) node.gridColumnGap = li.gridColumnGap;
    if (li.gridRowGap !== undefined) node.gridRowGap = li.gridRowGap;
    if (li.radius !== undefined) node.cornerRadius = li.radius;
    if (li.strokeWeight !== undefined) node.strokeWeight = li.strokeWeight;
    if (li.minWidth !== undefined) { try { node.minWidth = li.minWidth; } catch (e) { /* needs auto-layout */ } }
    if (li.minHeight !== undefined) { try { node.minHeight = li.minHeight; } catch (e) { /* needs auto-layout */ } }
    // #60 fix 1 (fillClear precedence): a spec-carried fill is NEVER
    // trampled — fillClear only clears when no fill was spec'd. The compile
    // side already drops fillClear when a fill binding exists (applyLiterals);
    // this runtime guard makes the emitted script safe even for hand-fed
    // specs carrying both.
    if (li.fillClear && !spec.fill) node.fills = [];
    else if (li.fillColor) node.fills = [{ type: 'SOLID', color: { r: li.fillColor.r, g: li.fillColor.g, b: li.fillColor.b }, opacity: li.fillColor.a === undefined ? 1 : li.fillColor.a }];
    if (li.strokeColor) node.strokes = [{ type: 'SOLID', color: { r: li.strokeColor.r, g: li.strokeColor.g, b: li.strokeColor.b }, opacity: li.strokeColor.a === undefined ? 1 : li.strokeColor.a }];
    if (li.radiusCorners) {
      const rc = li.radiusCorners;
      if (rc.tl !== undefined) node.topLeftRadius = rc.tl;
      if (rc.tr !== undefined) node.topRightRadius = rc.tr;
      if (rc.bl !== undefined) node.bottomLeftRadius = rc.bl;
      if (rc.br !== undefined) node.bottomRightRadius = rc.br;
    }
    if (li.strokeSides) {
      const sw = li.strokeSides;
      if (sw.top !== undefined) node.strokeTopWeight = sw.top;
      if (sw.right !== undefined) node.strokeRightWeight = sw.right;
      if (sw.bottom !== undefined) node.strokeBottomWeight = sw.bottom;
      if (sw.left !== undefined) node.strokeLeftWeight = sw.left;
      // 016: our grammar never expresses strokesIncludedInLayout — a true
      // inherited by an amend-reused node is a ghost fact (same class as
      // strokeClear): it inflated Footer.Separator to h=2 where the origin
      // LINE contributes 0. Normalize whenever we own the node's strokes.
      // (NB: this block lives inside a template literal — no backticks here.)
      // 016, measured live: a zero-height part with per-side strokes is a
      // LINE, not a box — INSIDE stroke align (the border-box doctrine, right
      // for boxes) makes Figma clamp the frame's height to the horizontal
      // stroke total (0 became 2). CENTER, like the origin LINE's own stroke,
      // leaves geometry at ~0; the weights were set after the bind-time
      // resize, so re-affirm the zero height last. (Zero-WIDTH vertical rules
      // would need the mirror rule — unproven, so not written.)
      if (spec.fixedHeight && spec.fixedHeight.px === 0) {
        node.strokeAlign = 'CENTER';
        node.resize(node.width, 0);
      }
      try { node.strokesIncludedInLayout = false; } catch (e) { /* not a frame */ }
    }
    if (li.width !== undefined || li.height !== undefined) {
      node.resize(li.width !== undefined ? li.width : node.width, li.height !== undefined ? li.height : node.height);
      const mode = (spec.layout || { mode: 'HORIZONTAL' }).mode;
      if (mode !== 'GRID') {
        const horizontalIsPrimary = mode === 'HORIZONTAL';
        if (li.width !== undefined) {
          if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED'; else node.counterAxisSizingMode = 'FIXED';
        }
        if (li.height !== undefined) {
          if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED'; else node.primaryAxisSizingMode = 'FIXED';
        }
      }
    }
  }
  // A growing image with a fixed master-height is a proportional image plane,
  // not a permanently tall crop. When a consumer narrows the component (the
  // 743px category card is used at 474px), Figma must scale that basis with
  // the width instead of retaining the master's 418px height.
  if (spec.imgPlaceholder && spec.grow && spec.fixedHeight && 'constrainProportions' in node) {
    node.constrainProportions = true;
  }
}

// v7 overlay: out-of-flow edge attachment. Must run AFTER appendChild —
// layoutPositioning ABSOLUTE requires an auto-layout parent.
function applyOverlay(parent, childNode, childSpec) {
  if (!childSpec.overlay) return;
  try {
    childNode.layoutPositioning = 'ABSOLUTE';
    const p = childSpec.overlay.placement;
    childNode.constraints =
      p === 'bottom' ? { horizontal: 'MIN', vertical: 'MAX' } :
      p === 'end' ? { horizontal: 'MAX', vertical: 'MIN' } :
      { horizontal: 'MIN', vertical: 'MIN' };
    if (p === 'top') { childNode.x = 0; childNode.y = -childNode.height; }
    else if (p === 'bottom') { childNode.x = 0; childNode.y = parent.height; }
    else if (p === 'start') { childNode.x = -childNode.width; childNode.y = 0; }
    else { childNode.x = parent.width; childNode.y = 0; }
  } catch (e) { /* parent not auto-layout — leave in flow */ }
}

// B-3 finding 5: an inset-0 overlay part (top/right/bottom/left all 0) is
// lowered out of flow — ABSOLUTE, stretched to the parent, BEHIND the
// in-flow siblings — matching the declared anatomy and the HTML render.
function applyInsetOverlay(parent, childNode, childSpec) {
  if (!childSpec.insetOverlay) return;
  try {
    // Round 5f (B5E finding 3): only a childless BACKDROP overlay (an
    // inset:0 fill layer — TextField's backdrop) lowers BEHIND the in-flow
    // siblings (index 0). A CONTENT overlay that carries glyphs (the Checkbox
    // check, the RadioButton dot, a remove button) must stay ON TOP at its
    // natural post-backdrop index — else the opaque backdrop sibling paints
    // over the glyph (the checkbox backdrop-over-glyph z-order the owner saw,
    // previously hand-corrected on canvas each re-amend).
    if (!childNode.children || childNode.children.length === 0) {
      parent.insertChild(0, childNode);
    }
    // Figma forbids FILL sizing on an absolute auto-layout child. The inset
    // constraints own the width after it leaves flow.
    if ('layoutSizingHorizontal' in childNode && childNode.layoutSizingHorizontal === 'FILL') childNode.layoutSizingHorizontal = 'FIXED';
    childNode.layoutPositioning = 'ABSOLUTE';
    const o = childSpec.insetOffsets || { top: 0, right: 0, bottom: 0, left: 0 };
    childNode.x = o.left;
    childNode.y = o.top;
    if (childSpec.insetPartialV) {
      // 016: top band — top/left/right pinned, NO bottom. The node keeps its
      // own (token-bound) height; only the width follows the parent.
      childNode.constraints = { horizontal: 'STRETCH', vertical: 'MIN' };
      childNode.resize(Math.max(1, parent.width - o.left - o.right), childNode.height);
    } else {
      childNode.constraints = { horizontal: 'STRETCH', vertical: 'STRETCH' };
      childNode.resize(
        Math.max(1, parent.width - o.left - o.right),
        Math.max(1, parent.height - o.top - o.bottom),
      );
    }
  } catch (e) { /* parent not auto-layout — leave in flow */ }
}

async function buildNode(spec, registry) {
  let node;
  if (spec.type === 'svg') {
    node = figma.createNodeFromSvg(spec.svg);
    node.fills = [];
    node.clipsContent = false;
    const svgWidth = spec.svgSize ? spec.svgSize.width : spec.iconSize;
    const svgHeight = spec.svgSize ? spec.svgSize.height : spec.iconSize;
    if (svgWidth && svgHeight) node.resize(svgWidth, svgHeight);
  } else if (spec.type === 'icon-instance') {
    const main = await findIconComponent(spec.iconComponent);
    node = main.createInstance();
    if (spec.iconSize) node.resize(spec.iconSize, spec.iconSize);
    registry.iconSwaps = registry.iconSwaps || [];
    registry.iconSwaps.push({ property: spec.iconSwapProperty, instance: node });
  } else if (spec.type === 'text') {
    node = figma.createText();
    node.fontName = await textFont(spec);
    node.fontSize = spec.fontSize || 16;
    node.characters = spec.characters || '';
    if (typeof spec.lineHeight === 'number') node.lineHeight = { unit: 'PIXELS', value: spec.lineHeight };
    if (typeof spec.letterSpacing === 'number') node.letterSpacing = { unit: 'PIXELS', value: spec.letterSpacing };
    if (spec.textCase) node.textCase = spec.textCase;
    if (spec.textDecoration) node.textDecoration = spec.textDecoration;
    if (spec.textAlignH) node.textAlignHorizontal = spec.textAlignH;
    if (spec.textTruncation) { try { node.textTruncation = 'ENDING'; } catch (e) { /* older API */ } }
    if (spec.textStyle) {
      // Exact-definition match compiled in: ride the named style. Text
      // styles own typography only — the bound fill paint below coexists.
      const st = await ourTextStyle(spec.textStyle);
      if (!st) throw new Error('Missing governed Text Style: ' + spec.textStyle);
      await node.setTextStyleIdAsync(st.id);
    }
    if (spec.textFill) node.fills = [boundPaint(spec.textFill, node)];
    if (spec.contentProp) {
      registry.texts.push({ prop: spec.contentProp, node, default: spec.characters || '' });
    }
    if (spec.fill || spec.fixedWidth || spec.fixedHeight || spec.bindings) {
      // Styled static text (page chips, dots, thumbs): wrap in a frame so
      // fills/dimensions/radius apply to a container, not the glyphs.
      const wrap = figma.createFrame();
      wrap.layoutMode = 'HORIZONTAL';
      wrap.primaryAxisAlignItems = 'CENTER';
      wrap.counterAxisAlignItems = 'CENTER';
      wrap.primaryAxisSizingMode = 'AUTO';
      wrap.counterAxisSizingMode = 'AUTO';
      wrap.fills = [];
      for (const [field, varName] of Object.entries(spec.bindings || {})) {
        wrap.setBoundVariable(field, need(varName));
      }
      if (spec.fill) wrap.fills = [boundPaint(spec.fill, wrap)];
      if (spec.stroke) { wrap.strokes = [boundPaint(spec.stroke, wrap)]; wrap.strokeAlign = 'INSIDE'; }
      if (spec.characters) wrap.appendChild(node); else node.remove();
      if (spec.fixedWidth || spec.fixedHeight) {
        wrap.resize(spec.fixedWidth ? spec.fixedWidth.px : wrap.width, spec.fixedHeight ? spec.fixedHeight.px : wrap.height);
        if (spec.fixedWidth) { wrap.primaryAxisSizingMode = 'FIXED'; wrap.setBoundVariable('width', need(spec.fixedWidth.varName)); }
        if (spec.fixedHeight) { wrap.counterAxisSizingMode = 'FIXED'; if (spec.fixedHeight.varName) wrap.setBoundVariable('height', need(spec.fixedHeight.varName)); else wrap.resize(wrap.width, spec.fixedHeight.px); }
        // 016, CSS semantics: width on a text block means the TEXT WRAPS at
        // that width. The wrapper was fixed but the TEXT stayed auto-width
        // (WIDTH_AND_HEIGHT) and overflowed in one line — measured live on
        // Devis.Titre: origin 900x100 (two lines), emitted TEXT 1498x50.
        if (spec.fixedWidth && spec.characters) {
          try {
            node.textAutoResize = 'HEIGHT';
            node.layoutSizingHorizontal = 'FILL';
          } catch (e) { /* older figma: leave auto */ }
        }
      }

      wrap.name = spec.name;
      node = wrap;
    }
  } else if (spec.type === 'instance') {
    const target = findComponentByName(spec.dep, spec.depId);
    const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
    node = main.createInstance();
    if (spec.depProps) setInstanceProps(node, spec.depProps);
    if (spec.depPropRefs && spec.depPropRefs.length > 0) {
      registry.forwards = registry.forwards || [];
      registry.forwards.push({ instance: node, mappings: spec.depPropRefs });
    }
    // v20 (016): contract-carried slot content on the composed instance — the
    // swap rides the child's INSTANCE_SWAP property (identity by marker, never
    // layer name), then the slotted instance's own props are set on the nested
    // instance the swap produced. Regenerated on every rebuild, by design.
    for (const ds of spec.depSlots || []) {
      const target = findComponentByName(ds.dep, ds.depId);
      const slotMain = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
      setInstanceProps(node, { [ds.property]: slotMain.id });
      // marker for the mock-backed fixture only — REAL Figma nodes are sealed
      // objects (assigning threw "object is not extensible" mid-amend, r11).
      try { node._depSlotsApplied = true; } catch (e) { /* sealed on canvas */ }
      if (ds.props && Object.keys(ds.props).length > 0) {
        const nested = [];
        for (const cand of (typeof node.findAll === 'function' ? node.findAll((n) => n.type === 'INSTANCE') : [])) {
          const mc = typeof cand.getMainComponentAsync === 'function' ? await cand.getMainComponentAsync() : null;
          if (mc && (mc.id === slotMain.id || (mc.parent && mc.parent.id === target.id))) nested.push(cand);
        }
        for (const inner of nested) setInstanceProps(inner, ds.props);
        if (nested.length === 0) {
          console.warn('[ds-contracts] depSlots: swapped ' + ds.property + ' to ' + ds.dep + ' but found no nested instance to receive its props (mock or detached child)');
        }
      }
    }
  } else if (spec.type === 'slot') {
    node = figma.createFrame();
    applyFrameSpec(node, spec);
    const defaults = spec.slotDefault || [];
    if (defaults.length === 0) {
      const util = await ensureSlotUtility();
      const inst = util.createInstance();
      node.appendChild(inst);
      registry.slots.push({ spec, wrapper: node, instance: inst, defaultId: null });
    } else {
      const instances = [];
      for (const item of defaults) {
        const target = findComponentByName(item.dep, item.depId);
        const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
        const inst = main.createInstance();
        if (item.props) setInstanceProps(inst, item.props);
        node.appendChild(inst);
        if (spec.layout && spec.layout.stretchChildren) {
          try { inst.layoutSizingHorizontal = 'FILL'; } catch (e) { /* fixed-size deps */ }
        }
        if (spec.slotControlStroke) {
          inst.strokes = [boundPaint(spec.slotControlStroke, inst)];
        }
        instances.push({ inst, main });
      }
      if (defaults.length === 1) {
        registry.slots.push({ spec, wrapper: node, instance: instances[0].inst, defaultId: instances[0].main.id });
      }
    }
  } else {
    node = spec.type === 'root' ? figma.createComponent() : figma.createFrame();
    applyFrameSpec(node, spec);
  }
  node.name = spec.name;
  if (spec.visibleProp) {
    registry.visibles.push({ node, prop: spec.visibleProp, default: spec.visibleDefault === true });
  }
  for (const child of spec.children || []) {
    const childNode = await buildNode(child, registry);
    node.appendChild(childNode);
    applyOverlay(node, childNode, child);
    if (child.pct != null) {
      try {
        childNode.resize(Math.max(1, Math.round(node.width * child.pct)), childNode.height);
        childNode.primaryAxisSizingMode = 'FIXED';
      } catch (e) { /* track not fixed-width */ }
    }
    if (
      child.type === 'frame' && (!child.children || child.children.length === 0) &&
      !child.fixedHeight && !(child.lits && child.lits.height !== undefined) && !child.shape
    ) {
      // #60 fix 4: empty runtime-sized geometry gets DECLARED defaults —
      // height follows the auto-layout parent (FILL), never Figma's 100×100
      // createFrame artifact (Phase B-2 finding 4: ProgressBar indicators
      // overflowed their fixed-height tracks). Width stays the spec'd
      // fraction (meter pct) or the placeholder box, named in the component
      // description.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    if (child.grow && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    } else if (
      spec.layout && spec.layout.stretchChildren &&
      !child.fixedWidth && child.type !== 'instance' &&
      'layoutSizingHorizontal' in childNode
    ) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    }


    // 016, CSS text-flow rule: in CSS every text wraps at its block's width —
    // Figma's auto-width has no CSS equivalent. A TEXT child of a
    // width-CONSTRAINED parent (fixed width, or a stretch/grow context)
    // fills and wraps (FILL + HEIGHT). Parents that HUG keep auto-width
    // text — that IS the inline semantics (button labels), and FILL inside
    // HUG is the circular case Figma refuses. Measured live: the
    // SectionHeader title overflowed Presentation's 628 column in one line
    // (origin: two lines) — the Devis.Titre fix was this rule's local case.
    if (childNode.type === 'TEXT' && (child.grow || spec.fixedWidth || (spec.layout && spec.layout.stretchChildren))) {
      try { childNode.textAutoResize = 'HEIGHT'; childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG parent */ }
    }
    applyInsetOverlay(node, childNode, child);
  }
  return node;
}


// djb2 over the compiled spec — stored on the set so unchanged components
// skip cheaply and CHANGED ones amend in place.
function specHash(C) {
  let h = 5381; const s = JSON.stringify(C);
  for (let i = 0; i < s.length; i++) h = (((h << 5) + h) + s.charCodeAt(i)) >>> 0;
  return String(h);
}

// IN-PLACE AMEND (2026-07-08, closes the create-only gap): reconcile an
// existing COMPONENT_SET against the compiled spec while preserving what
// instances bind to — the set node + key, each variant COMPONENT node, and
// existing componentProperty IDs. Variant interiors are contract-owned and
// rebuilt from spec (manual interior edits are drift by definition);
// instance-level property overrides survive because property IDs do.
// Destructive changes (extra variants from removed enum values) are
// REPORTED, never deleted — a human retires those.
// A real IMAGE paint on the canvas is an OUT-OF-CONTRACT override (capability
// matrix row 91, 2026-07-26 addendum): the contract carries the img part and
// its runtime URL prop, never the bytes. Both amend paths rebuild children
// from the spec, so the client's photos are HARVESTED before the teardown and
// RESTORED onto the rebuilt img parts. A contract-carried fill still wins
// (spec.fill wins, doctrine).
//
// ===== 017 — CE QUI A CHANGÉ, ET POURQUOI =====================================
// Le 2026-08-06, une régénération a effondré 62 photos sur 10 sections de 8
// maquettes du fichier client, DERRIÈRE UN RAPPORT VERT. Trois défauts, tous
// réparés ici — et le rapport ne peut plus être vert en présence d'une perte.
//
//  1. LE PÉRIMÈTRE. Le relevé ne voyait que le maître (comp). Or 255 des 349 photos
//     vivantes sont des surcharges d'INSTANCE DE PAGE (016/proofs/photos/
//     RECONCILIATION.md:26) : Figma propage la démolition aux instances, et les
//     surcharges meurent avec les nœuds qui les portaient — les trois quarts de
//     la population étaient hors de vue. Le relevé descend maintenant aux
//     instances du maître reconstruit, BORNÉ À LUI et jamais au fichier (un
//     parcours global sature le bac à sable, ≈5350 nœuds mesurés).
//  2. L'APPARIEMENT. Il se faisait par NOM, puis retombait sur « le premier
//     paint non réclamé » — un choix arbitraire qui rendait l'interversion
//     structurellement invisible. Il est maintenant POSITIONNEL : chemin exact
//     d'abord, puis ordre du document pour le reste. Le nom d'un calque du
//     canvas ne participe plus à AUCUNE comparaison (§VIII : un renommage n'est
//     pas une perte, deux homonymes ne se confondent pas).
//  3. L'ORDRE. La démolition précédait le calcul des accueils : au moment où
//     l'on découvrait qu'une photo n'avait nulle part où aller, le mal était
//     fait. Le REFUS est maintenant une PRÉ-PASSE exécutée AVANT le premier
//     remove() — aucun nœud touché (§X). Il se lève à la photo près, par un
//     acquittement écrit et imprimé, jamais par tolérance.
//
// CE QUI SUBSISTE DU REPLI, ET POURQUOI CE N'EST PLUS LE MÊME. Le « premier
// paint non réclamé » disparaît EN TANT QUE CHOIX ARBITRAIRE. Ce qui reste est
// un REHÉBERGEMENT d'ordre : une empreinte sans chemin exact prend l'accueil
// libre suivant DANS L'ORDRE DU DOCUMENT. C'est le cas réel du Hero — la photo
// est un fill de RACINE alors que le contrat modélise un enfant Background — et
// sans lui chaque régénération du Hero perdrait la photo du client (c'est le
// cas B de img-paint-preserved-on-amend, mesuré, pas hypothétique). Il est
// déterministe, il préserve l'ordre (donc il ne peut pas produire
// d'interversion), et il est RAPPORTÉ nommément dans rehebergees. Un
// rehébergement vers un accueil dont l'occupant d'origine est ailleurs est, lui,
// une INTERVERSION : il part dans deplacees et rend le rapport ROUGE.
// ==============================================================================

function cheminEnfantDe(chemin, i) { return chemin === '' ? String(i) : chemin + '/' + i; }
function comparerChemins(a, b) {
  const sa = a === '' ? [] : a.split('/').map(Number);
  const sb = b === '' ? [] : b.split('/').map(Number);
  for (let i = 0; i < Math.max(sa.length, sb.length); i++) {
    const x = sa[i] === undefined ? -1 : sa[i];
    const y = sb[i] === undefined ? -1 : sb[i];
    if (x !== y) return x - y;
  }
  return 0;
}
function noeudAuChemin(racine, chemin) {
  if (chemin === '') return racine;
  let n = racine;
  for (const seg of chemin.split('/')) {
    n = (n.children || [])[Number(seg)];
    if (!n) return null;
  }
  return n;
}
function cheminDuNoeud(racine, cible) {
  if (racine === cible) return '';
  const pile = [{ n: racine, c: '' }];
  while (pile.length > 0) {
    const t = pile.shift();
    const kids = t.n.children || [];
    for (let i = 0; i < kids.length; i++) {
      const ch = cheminEnfantDe(t.c, i);
      if (kids[i] === cible) return ch;
      pile.push({ n: kids[i], c: ch });
    }
  }
  return null;
}

// RELEVER — une empreinte, à son emplacement (hostId, cheminPosition).
function harvestImagePaints(node, pool, hostId, chemin) {
  const fills = Array.isArray(node.fills) ? node.fills : [];
  const imgs = fills.filter((f) => f && f.type === 'IMAGE');
  if (imgs.length > 0) {
    pool.push({
      hostId: hostId, cheminPosition: chemin, nomCalque: node.name,
      paints: imgs, claimed: false,
      // Une empreinte illisible est NON VÉRIFIABLE, jamais « identique » :
      // un contrôle empêché n'est pas un contrôle vert (FR-015).
      hashes: imgs.map((f) => (typeof f.imageHash === 'string' && f.imageHash !== '' ? f.imageHash : null)),
    });
  }
  const kids = node.children || [];
  for (let i = 0; i < kids.length; i++) harvestImagePaints(kids[i], pool, hostId, cheminEnfantDe(chemin, i));
}

// Les hôtes d'une reconstruction : le maître, PUIS ses instances de page.
// Deux voies nommées, et la frontière entre elles est écrite ici.
async function hotesDeReconstruction(comp) {
  const hotes = [{ node: comp, hostId: comp.id, hostNom: comp.name, role: 'master' }];
  let voie = 'aucune';
  let raison = null;
  // VOIE ÉPROUVÉE (repli nommé, research D1) : l'orchestrateur a relevé les
  // hôtes avant le lot et les passe par globalThis.__dsc_photos. Forme déjà
  // éprouvée au dépôt — specs/016-canvas-vrai/proofs/repose/photos-instances.json
  // (14 sections, 97 photos). Faiblesse à dire : elle exige un relevé frais
  // avant chaque lot, donc elle ne protège pas une régénération lancée sans
  // l'orchestrateur.
  const reg = (typeof globalThis !== 'undefined' && globalThis.__dsc_photos) || null;
  if (reg && Array.isArray(reg[comp.id])) {
    voie = 'registre-orchestre';
    for (const id of reg[comp.id]) {
      const n = await figma.getNodeByIdAsync(String(id));
      if (n) hotes.push({ node: n, hostId: n.id, hostNom: n.name, role: 'instance' });
    }
  } else if (typeof comp.getInstancesAsync === 'function') {
    // VOIE API — bornée au maître reconstruit, JAMAIS au fichier.
    // ⚠️ NON MESURÉE sur le fichier client au 2026-08-06 : la sonde T005 est
    // consignée empeche (specs/017-photos-honnetes/proofs/sonde-getinstances.md
    // — pont vivant mais saturé, EADDRINUSE sur toute la plage 9223-9232). Le
    // faux-Figma la modélise d'après l'API publiée, ce qui prouve que le moteur
    // emprunte correctement la voie, pas que le fichier client la rende.
    voie = 'getInstancesAsync';
    try {
      for (const inst of (await comp.getInstancesAsync()) || []) {
        hotes.push({ node: inst, hostId: inst.id, hostNom: inst.name, role: 'instance' });
      }
    } catch (e) {
      voie = 'empeche';
      raison = String((e && e.message) || e);
    }
  }
  return { hotes: hotes, voie: voie, raison: raison };
}

function collectImgSpecTargets(spec, out) {
  if (spec.imgPlaceholder === true && !spec.fill) out.push(spec.name);
  for (const ch of spec.children || []) collectImgSpecTargets(ch, out);
}
function findDescendantByName(node, name, dejaVus) {
  if (node.name === name && (!dejaVus || dejaVus.indexOf(node) < 0)) return node;
  for (const ch of node.children || []) {
    const hit = findDescendantByName(ch, name, dejaVus);
    if (hit) return hit;
  }
  return null;
}

// Les accueils, DANS L'ARBRE RECONSTRUIT, rendus par ordre de document.
// Le nom employé ici est celui du CONTRAT, sur un nœud que NOUS venons de bâtir
// — pas le nom d'un calque posé par un designer. §VIII interdit de se fier au
// second pour apparier ; il n'interdit pas de retrouver le nôtre.
function accueilsDuNoeud(rootNode, spec) {
  const noms = [];
  collectImgSpecTargets(spec, noms);
  const vus = [];
  const out = [];
  for (const nom of noms) {
    const n = findDescendantByName(rootNode, nom, vus);
    if (!n) continue;
    vus.push(n);
    out.push({ cheminPosition: cheminDuNoeud(rootNode, n), nom: nom });
  }
  out.sort((a, b) => comparerChemins(a.cheminPosition, b.cheminPosition));
  return out;
}

// Le registre gouverné des levées, baké au script (core/ ne lit aucun fichier).
// Les SEPT champs sont obligatoires et se refusent PAR LE NOM.
function chargerAcquittements() {
  const CHAMPS = ['hostId', 'cheminPosition', 'imageHash', 'motif', 'decidePar', 'decideLe', 'receiptId'];
  const out = [];
  for (let i = 0; i < ACQUITTEMENTS_PHOTOS.length; i++) {
    const e = ACQUITTEMENTS_PHOTOS[i];
    const manquants = CHAMPS.filter((c) => !e || typeof e[c] !== 'string' || e[c] === '');
    if (manquants.length > 0) {
      throw new Error(
        'REFUS au chargement du registre d\'acquittements photo (entrée ' + i + ') : champ(s) manquant(s) ou vide(s) — ' +
        manquants.join(', ') + '. Les sept champs sont obligatoires (hostId, cheminPosition, imageHash, motif, ' +
        'decidePar, decideLe, receiptId) : une porte fail-closed ne se lève pas sur une entrée incomplète.',
      );
    }
    out.push(e);
  }
  return out;
}

// ===== PRÉ-PASSE : RELEVER → COMPTER LES ACCUEILS → DÉCIDER ===================
// Rien de ce qui suit ne mute quoi que ce soit. Le refus, s'il tombe, tombe
// AVANT le premier remove() — c'est tout l'objet de FR-003a et de §X.
async function preparerSauvetagePhotos(comp, specs) {
  const info = await hotesDeReconstruction(comp);
  let accueilsAttendus = 0;
  for (const s of specs) {
    const noms = [];
    collectImgSpecTargets(s, noms);
    if (noms.length > accueilsAttendus) accueilsAttendus = noms.length;
  }
  const acquittes = chargerAcquittements();
  const parHote = [];
  const bloquantes = [];
  const levees = [];
  for (const h of info.hotes) {
    const entrees = [];
    harvestImagePaints(h.node, entrees, h.hostId, '');
    entrees.sort((a, b) => comparerChemins(a.cheminPosition, b.cheminPosition));
    const surplus = entrees.length - accueilsAttendus;
    for (let k = 0; k < surplus; k++) {
      const orpheline = entrees[entrees.length - 1 - k];
      const hash = orpheline.hashes[0];
      const acquit = acquittes.find((a) =>
        a.hostId === orpheline.hostId && a.cheminPosition === orpheline.cheminPosition && a.imageHash === hash);
      if (acquit) levees.push({ imageHash: hash, hostId: orpheline.hostId, cheminPosition: orpheline.cheminPosition, motif: acquit.motif, decidePar: acquit.decidePar, receiptId: acquit.receiptId });
      else bloquantes.push({ imageHash: hash, hostId: orpheline.hostId, cheminPosition: orpheline.cheminPosition, nomCalque: orpheline.nomCalque });
      orpheline.acquittee = !!acquit;
    }
    parHote.push({ hostId: h.hostId, hostNom: h.hostNom, role: h.role, node: h.node, entrees: entrees });
  }
  if (bloquantes.length > 0) {
    throw new Error(
      'REFUS AVANT MUTATION — ' + bloquantes.length + ' photo(s) relevée(s) n\'ont aucun emplacement d\'accueil ' +
      'dans le contrat reconstruit (' + accueilsAttendus + ' accueil(s) par hôte). AUCUN nœud n\'a été touché.\n' +
      bloquantes.map((b) => '  · imageHash=' + b.imageHash + ' hostId=' + b.hostId + ' cheminPosition=' + b.cheminPosition + ' (calque « ' + b.nomCalque + ' », documentaire)').join('\n') +
      '\nCe refus se lève à la photo près, par une entrée écrite dans ' +
      'specs/017-photos-honnetes/registre/acquittements-photos.json (sept champs obligatoires) — jamais par tolérance.',
    );
  }
  return { info: info, parHote: parHote, accueilsAttendus: accueilsAttendus, levees: levees };
}

// ===== REPOSER + RAPPORTER ====================================================
function restaurerPhotos(spec, comp, plan, report, contractId) {
  const accueils = accueilsDuNoeud(comp, spec);
  const hotes = [];
  for (const h of plan.parHote) {
    const libres = accueils.map((a) => a.cheminPosition);
    const pris = {};
    const retrouvees = [];
    const rehebergees = [];
    const deplacees = [];
    const nonReplacees = [];
    const nonVerifiables = [];
    const acquittees = [];
    const dispo = h.entrees.filter((e) => !e.acquittee);
    for (const e of dispo) {
      if (e.hashes.some((x) => x === null)) {
        nonVerifiables.push({ cheminPosition: e.cheminPosition, nomCalque: e.nomCalque, raison: 'imageHash absent — empreinte illisible' });
      }
    }
    // 1. chemin EXACT — le cas normal, la forme de l'arbre n'a pas bougé
    for (const e of dispo) {
      const i = libres.indexOf(e.cheminPosition);
      if (i < 0) continue;
      libres.splice(i, 1);
      pris[e.cheminPosition] = e;
      e.claimed = true;
      retrouvees.push({ cheminPosition: e.cheminPosition, imageHash: e.hashes[0] });
    }
    // 2. le reste, DANS L'ORDRE DU DOCUMENT — bijection déterministe
    for (const e of dispo) {
      if (e.claimed) continue;
      if (libres.length === 0) {
        nonReplacees.push({ cheminPosition: e.cheminPosition, imageHash: e.hashes[0], nomCalque: e.nomCalque });
        continue;
      }
      const vers = libres.shift();
      e.claimed = true;
      pris[vers] = e;
      const mouvement = { de: e.cheminPosition, vers: vers, imageHash: e.hashes[0] };
      // Si l'emplacement d'origine de cette empreinte est occupé par une AUTRE
      // empreinte, ce n'est pas un rehébergement : c'est une INTERVERSION.
      const occupant = dispo.find((o) => o !== e && o.cheminPosition === e.cheminPosition);
      if (occupant) deplacees.push(mouvement); else rehebergees.push(mouvement);
    }
    // 3. appliquer — RÉAFFECTATION du tableau, jamais mutation en place (dans
    //    le vrai Figma node.fills est readonly : une mutation en place est
    //    ignorée en silence).
    let distinctesApres = 0;
    const vusApres = {};
    for (const chemin of Object.keys(pris)) {
      const node = noeudAuChemin(h.node, chemin);
      if (!node) {
        nonReplacees.push({ cheminPosition: chemin, imageHash: pris[chemin].hashes[0], nomCalque: pris[chemin].nomCalque });
        continue;
      }
      node.fills = pris[chemin].paints;
      for (const x of pris[chemin].hashes) if (x && !vusApres[x]) { vusApres[x] = true; distinctesApres++; }
    }
    const vusAvant = {};
    let distinctesAvant = 0;
    for (const e of h.entrees) for (const x of e.hashes) if (x && !vusAvant[x]) { vusAvant[x] = true; distinctesAvant++; }
    for (const l of plan.levees) if (l.hostId === h.hostId) acquittees.push(l);
    hotes.push({
      hostId: h.hostId, hostNom: h.hostNom, role: h.role,
      attendues: h.entrees.length,
      retrouvees: retrouvees.length,
      distinctesAvant: distinctesAvant,
      distinctesApres: distinctesApres,
      deplacees: deplacees,
      rehebergees: rehebergees,
      nonReplacees: nonReplacees,
      nonVerifiables: nonVerifiables,
      acquittees: acquittees,
    });
    // trace héritée, conservée : les consommateurs existants la lisent
    for (const m of retrouvees) { report.preservedImages = report.preservedImages || []; report.preservedImages.push(h.hostId + ':' + m.cheminPosition); }
    for (const m of rehebergees) { report.preservedImages = report.preservedImages || []; report.preservedImages.push(h.hostId + ':' + m.de + ' -> ' + m.vers); }
    for (const m of nonReplacees) { report.unplacedImages = report.unplacedImages || []; report.unplacedImages.push(h.hostId + ':' + m.cheminPosition); }
  }
  // Le verdict, refusable par le nom (data-model §3). Le vert est INTERDIT si
  // une perte, une interversion ou une empreinte illisible existe quelque part.
  let verdict = 'vert';
  if (plan.info.voie === 'empeche') verdict = 'empeche';
  for (const h of hotes) {
    if (h.nonReplacees.length > 0 || h.deplacees.length > 0 || h.nonVerifiables.length > 0) verdict = 'rouge';
    // Le canal qui dit l'effondrement quand le compte total n'a pas bougé
    // (« 17 portraits distincts à l'origine, 2 au vif »).
    if (h.distinctesApres < h.distinctesAvant) verdict = 'rouge';
  }
  // amendSet boucle sur les variantes : le rapport s'ACCUMULE, il ne s'écrase
  // pas. Un seul hôte rouge suffit à rendre l'ensemble rouge.
  if (!report.photos) {
    report.photos = {
      schemaVersion: 1,
      contractId: contractId || null,
      voieInstances: plan.info.voie,
      raisonVoie: plan.info.raison,
      accueilsParHote: plan.accueilsAttendus,
      hotes: [],
      verdict: 'vert',
      refusAvantMutation: null,
    };
  }
  for (const h of hotes) report.photos.hotes.push(h);
  if (verdict === 'rouge' || report.photos.verdict === 'rouge') report.photos.verdict = 'rouge';
  else if (verdict === 'empeche' || report.photos.verdict === 'empeche') report.photos.verdict = 'empeche';
  if (plan.accueilsAttendus > report.photos.accueilsParHote) report.photos.accueilsParHote = plan.accueilsAttendus;
}

// Shared by amendSet and amendComponent (their only difference was the
// receiver): reconcile the target's governed property definitions with the
// contract — drop forwarded TEXT props, upsert BOOLEAN/TEXT defs and their
// defaults, upsert INSTANCE_SWAP defs against the governed icon registry.
async function upsertGovernedProperties(host, C, defs, newKeys, defKey, report) {
  for (const name of C.forwardedProps || []) {
    const k = defKey(name);
    if (k && defs[k]?.type === 'TEXT') {
      host.deleteComponentProperty(k);
      delete defs[k];
      report.removedForwardedProps = report.removedForwardedProps || [];
      report.removedForwardedProps.push(name);
    }
  }
  for (const w of [
    ...C.boolProps.map((bp) => ({ name: bp.property, type: 'BOOLEAN', def: bp.default })),
    ...(C.textProps || []).map((tp) => ({ name: tp.property, type: 'TEXT', def: tp.default })),
  ]) {
    const k = defKey(w.name);
    if (!k) { newKeys[w.name] = host.addComponentProperty(w.name, w.type, w.def); report.addedProps.push(w.name); }
    else if (defs[k].type === w.type && defs[k].defaultValue !== w.def) {
      host.editComponentProperty(k, { defaultValue: w.def });
      report.editedDefaults.push(w.name);
    }
  }
  for (const swap of C.swapProps || []) {
    const resolvedSwap = await iconSwapDefinition(swap);
    let k = defKey(swap.property);
    if (!k) {
      k = host.addComponentProperty(
        swap.property,
        'INSTANCE_SWAP',
        resolvedSwap.defaultId,
        { preferredValues: resolvedSwap.preferredValues },
      );
      newKeys[swap.property] = k;
      report.addedProps.push(swap.property);
    } else if (defs[k]?.type !== 'INSTANCE_SWAP') {
      throw new Error('Property type mismatch for governed icon swap: ' + swap.property);
    } else {
      const beforePreferred = JSON.stringify(defs[k].preferredValues || []);
      const afterPreferred = JSON.stringify(resolvedSwap.preferredValues);
      if (defs[k].defaultValue !== resolvedSwap.defaultId || beforePreferred !== afterPreferred) {
        host.editComponentProperty(k, {
          defaultValue: resolvedSwap.defaultId,
          preferredValues: resolvedSwap.preferredValues,
        });
        if (!report.editedDefaults.includes(swap.property)) report.editedDefaults.push(swap.property);
      }
    }
  }
}

// Shared amend epilogue (same receiver-only difference): bind every registry
// entry — TEXT characters, slot mains + optional visibility, visibility
// booleans, governed icon swaps — then expose composed-property forwards.
async function wireGovernedReferences(host, C, registry, defs, newKeys, defKey, report) {
  for (const t of registry.texts) {
    let k = defKey(t.prop);
    if (!k) { k = host.addComponentProperty(t.prop, 'TEXT', t.default); newKeys[t.prop] = k; report.addedProps.push(t.prop); }
    else if (defs[k] && defs[k].defaultValue !== t.default && !report.editedDefaults.includes(t.prop)) {
      host.editComponentProperty(k, { defaultValue: t.default });
      report.editedDefaults.push(t.prop);
    }
    t.node.componentPropertyReferences = { ...(t.node.componentPropertyReferences || {}), characters: k };
  }
  for (const sl of registry.slots) {
    const util = await ensureSlotUtility();
    let k = defKey(sl.spec.slotProperty);
    if (!k) {
      const preferred = [];
      for (const depName of sl.spec.slotAccepts || []) {
        const target = findComponentByName(depName);
        preferred.push({ type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT', key: target.key });
      }
      k = host.addComponentProperty(sl.spec.slotProperty, 'INSTANCE_SWAP', sl.defaultId || util.id,
        preferred.length > 0 ? { preferredValues: preferred } : undefined);
      newKeys[sl.spec.slotProperty] = k;
      report.addedProps.push(sl.spec.slotProperty);
    }
    sl.instance.componentPropertyReferences = { ...(sl.instance.componentPropertyReferences || {}), mainComponent: k };
    if (sl.spec.slotOptional) {
      let vk = defKey('Show ' + sl.spec.slotProperty);
      if (!vk) { vk = host.addComponentProperty('Show ' + sl.spec.slotProperty, 'BOOLEAN', true); newKeys['Show ' + sl.spec.slotProperty] = vk; }
      sl.wrapper.componentPropertyReferences = { ...(sl.wrapper.componentPropertyReferences || {}), visible: vk };
    }
  }
  for (const vis of registry.visibles) {
    const k = defKey(vis.prop);
    if (!k) continue;
    vis.node.componentPropertyReferences = { ...(vis.node.componentPropertyReferences || {}), visible: k };
    vis.node.visible = vis.default;
  }
  for (const swap of C.swapProps || []) {
    const k = defKey(swap.property);
    if (!k) throw new Error('Governed icon swap property missing after amend: ' + swap.property);
    wireIconSwapNodes(registry, swap.property, k);
  }
  wireDepPropForwards(registry);
}

async function amendSet(set, C) {
  set.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (set.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: set.id, key: set.key };
  }
  const report = { name: C.setName, amended: true, nodeId: set.id, key: set.key,
    addedVariants: [], rebuiltVariants: 0, extraVariants: [], addedProps: [], editedDefaults: [] };
  // 016: the variant-name reconciliation must run BEFORE the first
  // componentPropertyDefinitions read — on a set already in the incomplete-
  // names error state, THAT read throws and the repair below would never be
  // reached (measured live: SectionHeader gaining Emphase+Alignement).
  // Sets gaining/losing the State preview axis reconcile by RENAME, not
  // duplication: an existing variant whose name matches an expected name
  // minus the ', State=Default' segment IS that variant (instances point at
  // it), so it is renamed in place — every variant node ID is preserved.
  // Main-file finding, 2026-07-08: name-only matching built 12 duplicates
  // and stranded the 12 originals as off-axis extras.
  const EV = withStateAxis(C);
  const expected = new Map(EV.map((v) => [v.name, v]));
  for (const ch of set.children) {
    if (expected.has(ch.name)) continue;
    const gained = ch.name + ', State=Default';
    const lost = ch.name.replace(', State=Default', '');
    if (expected.has(gained) && !set.children.some((o) => o.name === gained)) {
      ch.name = gained;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(gained);
    } else if (lost !== ch.name && expected.has(lost) && !set.children.some((o) => o.name === lost)) {
      ch.name = lost;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(lost);
    } else {
      // 016, generalization of the State-axis rename: a set gaining ANY new
      // VARIANT dimension leaves its old variants named without the new
      // segments ("Disposition=Standard" vs "Disposition=Standard, Emphase=…").
      // Complete the old name with each missing expected axis at its spec
      // default — the old node IS that variant (instances point at it). If
      // this amend already built a twin under the completed name, the twin is
      // ours and instance-free: remove it, keep the historied node. Measured
      // live (SectionHeader +Emphase+Alignement): the incomplete pair put the
      // whole set in "existing errors" and every composite read failed.
      const segsOf = (nom) => new Map(nom.split(',').map((seg) => seg.trim().split('=')).filter((kv) => kv.length === 2).map(([k, val]) => [k, val]));
      const parsed = segsOf(ch.name);
      // the canonical default combo is EV[0] (row 0 / col 0 by construction):
      // missing axes complete at THEIR spec default, in EV[0]'s axis order.
      const defauts = segsOf(EV[0].name);
      let completed = null;
      if (parsed.size > 0 && parsed.size < defauts.size && [...parsed].every(([k]) => defauts.has(k))) {
        completed = [...defauts.keys()].map((k) => k + '=' + (parsed.has(k) ? parsed.get(k) : defauts.get(k))).join(', ');
        if (!expected.has(completed)) completed = null;
      }
      if (completed && completed !== ch.name) {
        const twin = set.children.find((o) => o !== ch && o.name === completed);
        // 016 revue adversariale (finding 1) : ne JAMAIS remove le jumeau — sous
        // le nouvel ordre (rename avant build) un jumeau peut être un node
        // PRÉEXISTANT portant des instances (designer migration) ; le supprimer
        // orphelinerait ses instances irréversiblement. On le renomme hors du
        // namespace gouverné et on le SIGNALE — un humain arbitre.
        if (twin) {
          twin.name = completed + ' (doublon amend — à arbitrer)';
          report.mergedVariants = report.mergedVariants || [];
          report.mergedVariants.push(completed + ' [jumeau conservé, renommé]');
          report.extraVariants.push(twin.name);
        }
        ch.name = completed;
        report.renamedVariants = report.renamedVariants || [];
        report.renamedVariants.push(completed);
      } else {
        report.extraVariants.push(ch.name);
      }
    }
  }
  const defs = set.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;
  await upsertGovernedProperties(set, C, defs, newKeys, defKey, report);

  const existingByName = new Map(set.children.map((ch) => [ch.name, ch]));

  for (const v of EV) {
    let comp = existingByName.get(v.name);
    const registry = { texts: [], slots: [], visibles: [] };
    let planConsommateurs = null;
    if (!comp) {
      comp = await buildNode(v.spec, registry);
      set.appendChild(comp);
      report.addedVariants.push(v.name);
    } else {
      // 017 — PRÉ-PASSE avant toute mutation : relever (maître ET instances de
      // page), compter les accueils, DÉCIDER. Une empreinte sans accueil jette
      // ICI, une ligne avant la première démolition (§X, FR-003a).
      const planPhotos = await preparerSauvetagePhotos(comp, [v.spec]);
      planConsommateurs = preparerSauvetageConsommateurs(comp, planPhotos.info);
      for (const child of [...comp.children]) child.remove();
      applyFrameSpec(comp, v.spec);
      for (const childSpec of v.spec.children || []) {
        const childNode = await buildNode(childSpec, registry);
        comp.appendChild(childNode);
        applyOverlay(comp, childNode, childSpec);
        if (childSpec.pct != null) {
          try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
        }
        if (
          childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
          !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
        ) {
          // #60 fix 4 (amend path): same empty-child declared default.
          try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
        }
        if (childSpec.grow && 'layoutSizingHorizontal' in childNode) {
          try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        } else if (v.spec.layout && v.spec.layout.stretchChildren && !childSpec.fixedWidth && childSpec.type !== 'instance' && 'layoutSizingHorizontal' in childNode) {
          try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        }


        // 016 CSS text-flow (see buildNode): TEXT in a width-constrained
        // variant root fills and wraps.
        if (childNode.type === 'TEXT' && (childSpec.grow || v.spec.fixedWidth || (v.spec.layout && v.spec.layout.stretchChildren))) {
          try { childNode.textAutoResize = 'HEIGHT'; childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        }
    applyInsetOverlay(comp, childNode, childSpec);
      }
      restaurerPhotos(v.spec, comp, planPhotos, report, C.contractId);
      report.rebuiltVariants++;
    }
    await wireGovernedReferences(set, C, registry, defs, newKeys, defKey, report);
    if (planConsommateurs) await restaurerSauvetageConsommateurs(planConsommateurs, report);
  }

  // Contract default combo must be the FIRST variant (Figma default = first).
  const first = set.children.find((ch) => ch.name === EV[0].name);
  if (first && set.children[0] !== first) set.insertChild(0, first);

  // Grid re-layout with the create path's math.
  const specByName = new Map(EV.map((sv) => [sv.name, sv]));
  const rowsN = Math.max(...EV.map((vv) => vv.row)) + 1;
  const colsN = Math.max(...EV.map((vv) => vv.col)) + 1;
  const colWs = new Array(colsN).fill(0);
  const rowHs = new Array(rowsN).fill(0);
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    colWs[sp.col] = Math.max(colWs[sp.col], child.width);
    rowHs[sp.row] = Math.max(rowHs[sp.row], child.height);
  }
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    let x = PAD, y = PAD;
    for (let i = 0; i < sp.col; i++) x += colWs[i] + PAD;
    for (let i = 0; i < sp.row; i++) y += rowHs[i] + PAD;
    child.x = x; child.y = y;
  }
  // B-3 finding 4: after re-gridding, the SET CONTAINER refits to the
  // children's extent + grid padding (the create path's exact math) —
  // without this, added variants/columns stayed clipped by stale bounds
  // (Banner's Focus column, Button's 220-cell grid, ProgressBar's height).
  // Extra (human-owned) variants may sit beyond the grid; never shrink
  // below their extent.
  {
    let totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    let totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    for (const child of set.children) {
      totalW = Math.max(totalW, child.x + child.width + PAD);
      totalH = Math.max(totalH, child.y + child.height + PAD);
    }
    set.resizeWithoutConstraints(totalW, totalH);
  }
  set.description = C.description;
  set.setSharedPluginData('ds_contracts', 'specHash', hash);
  return report;
}

// #60 fix 3: IN-PLACE AMEND for standalone COMPONENTs (non-set: Badge/Tag
// class) — the same identity-marker update semantics as amendSet: the
// component node (and key) instances bind to is preserved; the interior is
// contract-owned and rebuilt from spec; existing componentProperty IDs
// survive via defKey. Unchanged specs skip on the stored specHash.
async function amendComponent(comp, C) {
  comp.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (comp.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: comp.id, key: comp.key };
  }
  const report = { name: C.setName, amended: true, standalone: true, nodeId: comp.id, key: comp.key, addedProps: [], editedDefaults: [] };
  const defs = comp.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;
  await upsertGovernedProperties(comp, C, defs, newKeys, defKey, report);
  const v = C.variants[0];
  const registry = { texts: [], slots: [], visibles: [] };
  // 017 — même PRÉ-PASSE que le chemin amendSet : relever le maître ET ses
  // instances de page, compter les accueils, DÉCIDER. Le refus tombe ici, une
  // ligne avant la première démolition (§X, FR-003a).
  const planPhotos = await preparerSauvetagePhotos(comp, [v.spec]);
  const planConsommateurs = preparerSauvetageConsommateurs(comp, planPhotos.info);
  for (const child of [...comp.children]) child.remove();
  applyFrameSpec(comp, v.spec);
  for (const childSpec of v.spec.children || []) {
    const childNode = await buildNode(childSpec, registry);
    comp.appendChild(childNode);
    applyOverlay(comp, childNode, childSpec);
    if (childSpec.pct != null) {
      try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
    }
    if (
      childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
      !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
    ) {
      // #60 fix 4 (standalone amend path): same empty-child declared default.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    if (childSpec.grow && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    } else if (v.spec.layout && v.spec.layout.stretchChildren && !childSpec.fixedWidth && childSpec.type !== 'instance' && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    }


    // 016 CSS text-flow (see buildNode): TEXT in a width-constrained root
    // fills and wraps.
    if (childNode.type === 'TEXT' && (childSpec.grow || v.spec.fixedWidth || (v.spec.layout && v.spec.layout.stretchChildren))) {
      try { childNode.textAutoResize = 'HEIGHT'; childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    }
    applyInsetOverlay(comp, childNode, childSpec);
  }
  restaurerPhotos(v.spec, comp, planPhotos, report, C.contractId);
  await wireGovernedReferences(comp, C, registry, defs, newKeys, defKey, report);
  await restaurerSauvetageConsommateurs(planConsommateurs, report);
  comp.description = C.description;
  comp.setSharedPluginData('ds_contracts', 'specHash', hash);
  return report;
}

async function syncOne(C) {
  // Identity is the ds_contracts/contractId marker, NOT the set name — in a
  // brownfield file a name can belong to the host system's own component
  // (CBDS pilot: native 72-variant "Badge"). Legacy fallback: sets created
  // before the marker existed carry only specHash under the same namespace.
  let existing = null;
  for (const page of figma.root.children) {
    existing = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') &&
        n.getSharedPluginData('ds_contracts', 'contractId') === C.contractId,
    );
    if (existing) break;
  }
  if (!existing) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName &&
          n.getSharedPluginData('ds_contracts', 'specHash') !== '',
      );
      if (existing) break;
    }
  }
  // An anchored key is ours by definition — the contract records the key the
  // canvas minted. Covers legacy nodes that predate both plugin-data markers
  // (main-file finding, 2026-07-08: 17 standalone components duplicated).
  if (!existing && C.anchorKey) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.key === C.anchorKey,
      );
      if (existing) break;
    }
    if (existing) existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  }
  if (existing && existing.type === 'COMPONENT_SET' && C.isSet) {
    return await amendSet(existing, C);
  }
  // #60 fix 3: standalone COMPONENTs (Badge/Tag class) amend in place too —
  // the "amend supports variant sets in v1" skip forced delete+recreate and
  // re-minted node ids/keys (Phase B-2 named finding 2).
  if (existing && existing.type === 'COMPONENT' && !C.isSet) {
    return await amendComponent(existing, C);
  }
  if (existing) {
    existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
    return { name: C.setName, skipped: true, reason: 'set/standalone shape mismatch (' + existing.type + ' vs isSet=' + C.isSet + ') — a human retires the old node', nodeId: existing.id, key: existing.key };
  }

  // A same-named unmarked set is foreign: leave it alone, disambiguate ours.
  let displayName = C.setName;
  for (const page of figma.root.children) {
    const foreign = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName,
    );
    if (foreign) { displayName = C.setName + ' (' + C.contractId + ')'; break; }
  }

  // One page per component (see figma-sync/arrange.js for the file layout).
  let compPage = figma.root.children.find((p) => p.name === displayName);
  if (!compPage) { compPage = figma.createPage(); compPage.name = displayName; }

  const EV = withStateAxis(C);
  const built = [];
  for (const v of EV) {
    const registry = { texts: [], slots: [], visibles: [] };
    const comp = await buildNode(v.spec, registry);
    built.push({ v, comp, registry });
  }
  for (const b of built) {
    for (const t of b.registry.texts) {
      const key = b.comp.addComponentProperty(t.prop, 'TEXT', t.default);
      t.node.componentPropertyReferences = { ...(t.node.componentPropertyReferences || {}), characters: key };
    }
    for (const s of b.registry.slots) {
      const util = await ensureSlotUtility();
      const preferred = [];
      for (const depName of s.spec.slotAccepts || []) {
        const target = findComponentByName(depName);
        preferred.push({
          type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT',
          key: target.key,
        });
      }
      const key = b.comp.addComponentProperty(
        s.spec.slotProperty,
        'INSTANCE_SWAP',
        s.defaultId || util.id,
        preferred.length > 0 ? { preferredValues: preferred } : undefined,
      );
      s.instance.componentPropertyReferences = { ...(s.instance.componentPropertyReferences || {}), mainComponent: key };
      if (s.spec.slotOptional) {
        const vkey = b.comp.addComponentProperty('Show ' + s.spec.slotProperty, 'BOOLEAN', true);
        s.wrapper.componentPropertyReferences = { ...(s.wrapper.componentPropertyReferences || {}), visible: vkey };
      }
    }
    const boolKeys = {};
    for (const bp of C.boolProps) {
      boolKeys[bp.property] = b.comp.addComponentProperty(bp.property, 'BOOLEAN', bp.default);
    }
    for (const tp of C.textProps || []) {
      b.comp.addComponentProperty(tp.property, 'TEXT', tp.default);
    }
    for (const swap of C.swapProps || []) {
      const resolvedSwap = await iconSwapDefinition(swap);
      const key = b.comp.addComponentProperty(
        swap.property,
        'INSTANCE_SWAP',
        resolvedSwap.defaultId,
        { preferredValues: resolvedSwap.preferredValues },
      );
      wireIconSwapNodes(b.registry, swap.property, key);
    }
    for (const vis of b.registry.visibles) {
      const key = boolKeys[vis.prop];
      if (!key) continue;
      vis.node.componentPropertyReferences = { ...(vis.node.componentPropertyReferences || {}), visible: key };
      vis.node.visible = vis.default;
    }
    wireDepPropForwards(b.registry);
  }

  let target;
  if (C.isSet) {
    // combineAsVariants requires the nodes to already be ON the parent page.
    for (const b of built) compPage.appendChild(b.comp);
    target = figma.combineAsVariants(built.map((b) => b.comp), compPage);
    // Tight grid: rows = first axis, columns = second; per-track max sizing.
    const specByName = new Map(EV.map((s) => [s.name, s]));
    const rowsN = Math.max(...EV.map((v) => v.row)) + 1;
    const colsN = Math.max(...EV.map((v) => v.col)) + 1;
    const colWs = new Array(colsN).fill(0);
    const rowHs = new Array(rowsN).fill(0);
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      colWs[spec.col] = Math.max(colWs[spec.col], child.width);
      rowHs[spec.row] = Math.max(rowHs[spec.row], child.height);
    }
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      let x = PAD, y = PAD;
      for (let i = 0; i < spec.col; i++) x += colWs[i] + PAD;
      for (let i = 0; i < spec.row; i++) y += rowHs[i] + PAD;
      child.x = x;
      child.y = y;
    }
    const totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    const totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    target.resizeWithoutConstraints(totalW, totalH);
  } else {
    target = built[0].comp;
    compPage.appendChild(target);
  }
  target.name = displayName;
  target.description = C.description;
  target.x = 100;
  target.y = 100;
  target.setSharedPluginData('ds_contracts', 'specHash', specHash(C));
  target.setSharedPluginData('ds_contracts', 'contractId', C.contractId);

  return {
    name: C.setName,
    nodeId: target.id,
    key: target.key,
    variants: C.isSet ? target.children.length : 1,
    properties: Object.keys(target.componentPropertyDefinitions || {}),
  };
}

const results = [];
for (const C of COMPONENTS) {
  results.push(await syncOne(C));
}
return { createdNodeIds: results.filter((r) => !r.skipped).map((r) => r.nodeId), results, fontFallbacks };
