// GENERATED by scripts/generate-figma.ts — DO NOT EDIT.
// Batch sync: Button, Checkbox, ReviewCard, GoogleReviews, Input, Select, Textarea (unchanged components skip; changed ones amend in place).
const COMPONENTS = [
  {
    "setName": "Button",
    "contractId": "ds.button",
    "anchorKey": "e6fa6786ed120eb3f3507024f8cda9058ae661c6",
    "description": "Button — generated from contract ds.button v1.5.0",
    "isSet": true,
    "boolProps": [
      {
        "property": "Icône gauche",
        "default": false
      },
      {
        "property": "Icône droite",
        "default": false
      }
    ],
    "textProps": [],
    "fontStyles": [
      "Medium"
    ],
    "variants": [
      {
        "name": "Property 1=Default",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Default",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/16",
            "paddingBottom": "space/16",
            "paddingLeft": "space/32",
            "paddingRight": "space/32",
            "strokeWeight": "border-width/0"
          },
          "fill": "color/noir-bleute",
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/blanc",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      },
      {
        "name": "Property 1=Orange",
        "row": 1,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Orange",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/16",
            "paddingBottom": "space/16",
            "paddingLeft": "space/32",
            "paddingRight": "space/32",
            "strokeWeight": "border-width/0"
          },
          "fill": "color/orange",
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/blanc",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      },
      {
        "name": "Property 1=Blanc",
        "row": 2,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Blanc",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/16",
            "paddingBottom": "space/16",
            "paddingLeft": "space/32",
            "paddingRight": "space/32",
            "strokeWeight": "border-width/0"
          },
          "fill": "color/blanc",
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/noir-bleute",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      },
      {
        "name": "Property 1=Outline blanc",
        "row": 3,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Outline blanc",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/16",
            "paddingBottom": "space/16",
            "paddingLeft": "space/32",
            "paddingRight": "space/32",
            "strokeWeight": "border-width/2"
          },
          "stroke": "color/blanc",
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/blanc",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#FFFFFF\"/>\n</svg>",
              "svgPaintVar": "color/blanc",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      },
      {
        "name": "Property 1=Link",
        "row": 4,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Link",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/4",
            "paddingBottom": "space/4",
            "paddingLeft": "space/0",
            "paddingRight": "space/0",
            "strokeWeight": "border-width/0",
            "topLeftRadius": "radius/32",
            "topRightRadius": "radius/32",
            "bottomLeftRadius": "radius/32",
            "bottomRightRadius": "radius/32"
          },
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/noir-bleute",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      },
      {
        "name": "Property 1=Outilne noir",
        "row": 5,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Property 1=Outilne noir",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "itemSpacing": "space/10",
            "paddingTop": "space/16",
            "paddingBottom": "space/16",
            "paddingLeft": "space/32",
            "paddingRight": "space/32",
            "strokeWeight": "border-width/2"
          },
          "stroke": "color/noir-bleute",
          "children": [
            {
              "type": "svg",
              "name": "iconLeft",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.4271 9.375H3.12861L6.87842 5.6252L5.99455 4.74133L0.73584 10L5.99455 15.2588L6.87842 14.3749L3.12854 10.625H19.4271V9.375Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône gauche",
              "visibleDefault": false
            },
            {
              "type": "text",
              "name": "label",
              "characters": "Contactez-nous",
              "fontSize": 16,
              "fontStyle": "Medium",
              "textFill": "color/noir-bleute",
              "lineHeight": 22,
              "textCase": "UPPER",
              "fontFamily": "Montserrat",
              "contentProp": "Libellé"
            },
            {
              "type": "svg",
              "name": "iconRight",
              "svg": "<svg width=\"20\" height=\"20\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M14.0575 4.74133L13.1737 5.6252L16.9236 9.37508H0.625V10.6251H16.9234L13.1737 14.3749L14.0575 15.2588L19.3163 10L14.0575 4.74133Z\" fill=\"#26282C\"/>\n</svg>",
              "svgPaintVar": "color/noir-bleute",
              "iconSize": 20,
              "visibleProp": "Icône droite",
              "visibleDefault": false
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "Checkbox",
    "contractId": "ds.checkbox",
    "anchorKey": "d1b5e763513013c8d216d840c4f95f22f0e3c909",
    "description": "Checkbox — generated from contract ds.checkbox v1.0.0",
    "isSet": true,
    "boolProps": [],
    "textProps": [],
    "fontStyles": [
      "Medium"
    ],
    "variants": [
      {
        "name": "Coché=Non",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Coché=Non",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "strokeWeight": "border-width/2"
          },
          "fill": "color/blanc",
          "stroke": "color/bleu-gris",
          "lits": {
            "width": 20,
            "height": 20,
            "radius": 0
          },
          "children": []
        }
      },
      {
        "name": "Coché=Oui",
        "row": 1,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Coché=Oui",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "CENTER",
            "counter": "CENTER"
          },
          "bindings": {
            "strokeWeight": "border-width/2"
          },
          "fill": "color/bleu",
          "stroke": "color/bleu",
          "lits": {
            "width": 20,
            "height": 20,
            "radius": 0
          },
          "children": [
            {
              "type": "svg",
              "name": "checkGlyph",
              "svg": "<svg width=\"13\" height=\"13\" viewBox=\"0 0 13 10\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M1 5.4L4.5 9L11.5 1\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>",
              "iconSize": 13
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "ReviewCard",
    "contractId": "ds.review-card",
    "anchorKey": null,
    "description": "ReviewCard — generated from contract ds.review-card v1.0.0 †",
    "isSet": false,
    "boolProps": [
      {
        "property": "Tronqué",
        "default": false
      },
      {
        "property": "Avatar initiale",
        "default": true
      },
      {
        "property": "Avatar photo",
        "default": false
      },
      {
        "property": "Vérifié",
        "default": true
      }
    ],
    "textProps": [
      {
        "property": "URL photo",
        "default": ""
      },
      {
        "property": "Alt photo",
        "default": ""
      }
    ],
    "fontStyles": [
      "Medium",
      "Semi Bold"
    ],
    "variants": [
      {
        "name": "ReviewCard",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "ReviewCard",
          "layout": {
            "mode": "VERTICAL",
            "primary": "MIN",
            "counter": "MIN",
            "stretchChildren": true
          },
          "fill": "color/blanc",
          "stroke": "color/bleu-clair",
          "lits": {
            "width": 299,
            "minHeight": 239,
            "radius": 8,
            "strokeWeight": 1,
            "paddingTop": 24,
            "paddingBottom": 24,
            "paddingLeft": 24,
            "paddingRight": 24,
            "itemSpacing": 14
          },
          "children": [
            {
              "type": "frame",
              "name": "entete",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "SPACE_BETWEEN",
                "counter": "CENTER"
              },
              "children": [
                {
                  "type": "frame",
                  "name": "profil",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "MIN",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "itemSpacing": 12
                  },
                  "children": [
                    {
                      "type": "frame",
                      "name": "avatarInitiale",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "CENTER",
                        "counter": "CENTER"
                      },
                      "fill": "color/bleu-gris",
                      "lits": {
                        "width": 40,
                        "height": 40,
                        "minWidth": 40,
                        "radius": 20
                      },
                      "children": [
                        {
                          "type": "text",
                          "name": "initialeTexte",
                          "characters": "P",
                          "fontSize": 18,
                          "fontStyle": "Semi Bold",
                          "textFill": "color/blanc",
                          "lineHeight": 1,
                          "fontFamily": "Montserrat",
                          "contentProp": "Initiale"
                        }
                      ],
                      "visibleProp": "Avatar initiale",
                      "visibleDefault": true
                    },
                    {
                      "type": "frame",
                      "name": "avatarPhoto",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "MIN",
                        "counter": "MIN"
                      },
                      "lits": {
                        "width": 40,
                        "height": 40,
                        "minWidth": 40,
                        "radius": 20,
                        "fillColor": {
                          "r": 0.8509803921568627,
                          "g": 0.8509803921568627,
                          "b": 0.8509803921568627
                        }
                      },
                      "imgPlaceholder": true,
                      "children": [],
                      "visibleProp": "Avatar photo",
                      "visibleDefault": false
                    },
                    {
                      "type": "frame",
                      "name": "identite",
                      "layout": {
                        "mode": "VERTICAL",
                        "primary": "CENTER",
                        "counter": "MIN",
                        "stretchChildren": true
                      },
                      "lits": {
                        "itemSpacing": 2
                      },
                      "children": [
                        {
                          "type": "text",
                          "name": "auteur",
                          "characters": "Prénom N.",
                          "fontSize": 16,
                          "fontStyle": "Semi Bold",
                          "lineHeight": 1.2,
                          "fontFamily": "Montserrat",
                          "contentProp": "Auteur"
                        },
                        {
                          "type": "text",
                          "name": "date",
                          "characters": "il y a 2 mois",
                          "fontSize": 14,
                          "fontStyle": "Medium",
                          "lineHeight": 1.2,
                          "fontFamily": "Montserrat",
                          "contentProp": "Date"
                        }
                      ]
                    }
                  ]
                },
                {
                  "type": "svg",
                  "name": "marque",
                  "svg": "<svg width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z\" fill=\"#4285F4\"/>\n<path d=\"M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z\" fill=\"#34A853\"/>\n<path d=\"M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z\" fill=\"#FBBC05\"/>\n<path d=\"M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z\" fill=\"#EA4335\"/>\n</svg>",
                  "iconSize": 18
                }
              ]
            },
            {
              "type": "frame",
              "name": "notation",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "MIN",
                "counter": "CENTER"
              },
              "lits": {
                "itemSpacing": 8
              },
              "children": [
                {
                  "type": "frame",
                  "name": "etoiles",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "MIN",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "itemSpacing": 3
                  },
                  "children": [
                    {
                      "type": "svg",
                      "name": "etoile1",
                      "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                      "iconSize": 16
                    },
                    {
                      "type": "svg",
                      "name": "etoile2",
                      "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                      "iconSize": 16
                    },
                    {
                      "type": "svg",
                      "name": "etoile3",
                      "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                      "iconSize": 16
                    },
                    {
                      "type": "svg",
                      "name": "etoile4",
                      "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                      "iconSize": 16
                    },
                    {
                      "type": "svg",
                      "name": "etoile5",
                      "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                      "iconSize": 16
                    }
                  ]
                },
                {
                  "type": "frame",
                  "name": "verification",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "CENTER",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "width": 16,
                    "height": 16,
                    "minWidth": 16,
                    "radius": 8,
                    "fillColor": {
                      "r": 0,
                      "g": 0,
                      "b": 0
                    }
                  },
                  "children": [
                    {
                      "type": "svg",
                      "name": "coche",
                      "svg": "<svg width=\"10\" height=\"10\" viewBox=\"0 0 13 10\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M1 5.4L4.5 9L11.5 1\" stroke=\"white\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/>\n</svg>",
                      "iconSize": 10
                    }
                  ],
                  "visibleProp": "Vérifié",
                  "visibleDefault": true
                }
              ]
            },
            {
              "type": "text",
              "name": "temoignage",
              "characters": "Un témoignage neutre, exemple générique de contenu.",
              "fontSize": 14,
              "fontStyle": "Medium",
              "lineHeight": 1.4,
              "fontFamily": "Montserrat",
              "contentProp": "Témoignage"
            },
            {
              "type": "text",
              "name": "lireLaSuite",
              "characters": "Lire la suite",
              "fontSize": 14,
              "fontStyle": "Medium",
              "fontFamily": "Montserrat",
              "visibleProp": "Tronqué",
              "visibleDefault": false
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "GoogleReviews",
    "contractId": "ds.google-reviews",
    "anchorKey": null,
    "description": "GoogleReviews — generated from contract ds.google-reviews v1.0.0",
    "isSet": false,
    "boolProps": [
      {
        "property": "Contrôles",
        "default": true
      }
    ],
    "textProps": [],
    "fontStyles": [
      "Medium",
      "Semi Bold"
    ],
    "variants": [
      {
        "name": "GoogleReviews",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "GoogleReviews",
          "layout": {
            "mode": "VERTICAL",
            "primary": "MIN",
            "counter": "MIN",
            "stretchChildren": true
          },
          "fill": "color/blanc",
          "lits": {
            "height": 328,
            "itemSpacing": 12,
            "paddingTop": 4,
            "paddingBottom": 8,
            "paddingLeft": 11,
            "paddingRight": 11
          },
          "children": [
            {
              "type": "frame",
              "name": "resume",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "SPACE_BETWEEN",
                "counter": "CENTER"
              },
              "fill": "color/blanc",
              "stroke": "color/bleu-clair",
              "lits": {
                "radius": 8,
                "strokeWeight": 1,
                "paddingTop": 12,
                "paddingBottom": 12,
                "paddingLeft": 16,
                "paddingRight": 16
              },
              "children": [
                {
                  "type": "frame",
                  "name": "infos",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "MIN",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "itemSpacing": 10
                  },
                  "children": [
                    {
                      "type": "svg",
                      "name": "marque",
                      "svg": "<svg width=\"74\" height=\"24\" viewBox=\"0 0 74 24\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<text x=\"0\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#4285F4\">G</text>\n<text x=\"18\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#EA4335\">o</text>\n<text x=\"32\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#FBBC05\">o</text>\n<text x=\"46\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#4285F4\">g</text>\n<text x=\"60\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#34A853\">l</text>\n<text x=\"66\" y=\"18\" font-family=\"Montserrat, sans-serif\" font-size=\"22\" font-weight=\"500\" fill=\"#EA4335\">e</text>\n</svg>"
                    },
                    {
                      "type": "text",
                      "name": "qualificatifTexte",
                      "characters": "Excellent",
                      "fontSize": 14,
                      "fontStyle": "Semi Bold",
                      "fontFamily": "Montserrat",
                      "contentProp": "Qualificatif"
                    },
                    {
                      "type": "frame",
                      "name": "notation",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "MIN",
                        "counter": "CENTER"
                      },
                      "lits": {
                        "itemSpacing": 2
                      },
                      "children": [
                        {
                          "type": "svg",
                          "name": "etoile1",
                          "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                          "iconSize": 16
                        },
                        {
                          "type": "svg",
                          "name": "etoile2",
                          "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                          "iconSize": 16
                        },
                        {
                          "type": "svg",
                          "name": "etoile3",
                          "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                          "iconSize": 16
                        },
                        {
                          "type": "svg",
                          "name": "etoile4",
                          "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                          "iconSize": 16
                        },
                        {
                          "type": "svg",
                          "name": "etoile5",
                          "svg": "<svg width=\"16\" height=\"16\" viewBox=\"0 0 20 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M10 0L12.645 6.35942L19.5106 6.90983L14.2798 11.3906L15.8779 18.0902L10 14.5L4.12215 18.0902L5.72025 11.3906L0.489435 6.90983L7.35497 6.35942L10 0Z\" fill=\"#F98A0B\"/>\n</svg>",
                          "iconSize": 16
                        },
                        {
                          "type": "text",
                          "name": "noteGlobaleTexte",
                          "characters": "4.8",
                          "fontSize": 14,
                          "fontStyle": "Semi Bold",
                          "fontFamily": "Montserrat",
                          "contentProp": "Note globale"
                        }
                      ]
                    },
                    {
                      "type": "text",
                      "name": "separateur",
                      "characters": "|",
                      "fontSize": 14,
                      "fontStyle": "Medium",
                      "fontFamily": "Montserrat"
                    },
                    {
                      "type": "text",
                      "name": "volume",
                      "characters": "93 avis",
                      "fontSize": 14,
                      "fontStyle": "Medium",
                      "fontFamily": "Montserrat",
                      "contentProp": "Volume"
                    }
                  ]
                },
                {
                  "type": "frame",
                  "name": "ecrireAvis",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "CENTER",
                    "counter": "CENTER"
                  },
                  "stroke": "color/noir",
                  "lits": {
                    "strokeWeight": 1,
                    "radius": 0,
                    "paddingTop": 8,
                    "paddingBottom": 8,
                    "paddingLeft": 22,
                    "paddingRight": 22
                  },
                  "children": [
                    {
                      "type": "text",
                      "name": "libelle",
                      "characters": "Écrire un avis",
                      "fontSize": 14,
                      "fontStyle": "Semi Bold",
                      "fontFamily": "Montserrat"
                    }
                  ]
                }
              ]
            },
            {
              "type": "frame",
              "name": "cartes",
              "layout": {
                "mode": "HORIZONTAL",
                "primary": "SPACE_BETWEEN",
                "counter": "MIN",
                "stretchChildren": true
              },
              "children": [
                {
                  "type": "frame",
                  "name": "flecheGauche",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "CENTER",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "width": 0,
                    "minWidth": 0
                  },
                  "children": [
                    {
                      "type": "frame",
                      "name": "pastilleGauche",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "CENTER",
                        "counter": "CENTER"
                      },
                      "fill": "color/blanc",
                      "stroke": "color/bleu-clair",
                      "lits": {
                        "width": 30,
                        "height": 30,
                        "minWidth": 30,
                        "radius": 15,
                        "strokeWeight": 1
                      },
                      "children": [
                        {
                          "type": "svg",
                          "name": "iconeGauche",
                          "svg": "<svg width=\"14\" height=\"14\" viewBox=\"0 0 32 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M19.293 7.29302C19.6835 6.90249 20.3165 6.90249 20.707 7.29302C21.0975 7.68354 21.0975 8.31655 20.707 8.70708L13.414 16L20.707 23.293C21.0975 23.6835 21.0975 24.3166 20.707 24.7071C20.3165 25.0976 19.6835 25.0976 19.293 24.7071L11.293 16.7071C10.9024 16.3166 10.9024 15.6835 11.293 15.293L19.293 7.29302Z\" fill=\"#000000\"/>\n</svg>",
                          "iconSize": 14
                        }
                      ]
                    }
                  ],
                  "visibleProp": "Contrôles",
                  "visibleDefault": true
                },
                {
                  "type": "frame",
                  "name": "groupeCartes",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "MIN",
                    "counter": "MIN",
                    "stretchChildren": true
                  },
                  "grow": true,
                  "lits": {
                    "itemSpacing": 8
                  },
                  "children": [
                    {
                      "type": "instance",
                      "name": "carte",
                      "dep": "ReviewCard",
                      "depProps": {
                        "Auteur": "Prénom N.",
                        "Initiale": "P",
                        "Date": "il y a 2 mois",
                        "Témoignage": "Un témoignage neutre, exemple générique de contenu.",
                        "Avatar initiale": true,
                        "Avatar photo": false,
                        "URL photo": "",
                        "Alt photo": "",
                        "Vérifié": true,
                        "Tronqué": false
                      }
                    },
                    {
                      "type": "instance",
                      "name": "carte 2",
                      "dep": "ReviewCard",
                      "depProps": {
                        "Auteur": "Prénom N.",
                        "Initiale": "P",
                        "Date": "il y a 3 mois",
                        "Témoignage": "Un témoignage neutre, exemple générique de contenu.",
                        "Avatar initiale": true,
                        "Avatar photo": false,
                        "URL photo": "",
                        "Alt photo": "",
                        "Vérifié": true,
                        "Tronqué": false
                      }
                    },
                    {
                      "type": "instance",
                      "name": "carte 3",
                      "dep": "ReviewCard",
                      "depProps": {
                        "Auteur": "Prénom N.",
                        "Initiale": "P",
                        "Date": "il y a 4 mois",
                        "Témoignage": "Un témoignage neutre, exemple générique de contenu.",
                        "Avatar initiale": true,
                        "Avatar photo": false,
                        "URL photo": "",
                        "Alt photo": "",
                        "Vérifié": true,
                        "Tronqué": false
                      }
                    },
                    {
                      "type": "instance",
                      "name": "carte 4",
                      "dep": "ReviewCard",
                      "depProps": {
                        "Auteur": "Prénom N.",
                        "Initiale": "P",
                        "Date": "il y a 5 mois",
                        "Témoignage": "Un témoignage neutre, exemple générique de contenu.",
                        "Avatar initiale": true,
                        "Avatar photo": false,
                        "URL photo": "",
                        "Alt photo": "",
                        "Vérifié": true,
                        "Tronqué": false
                      }
                    },
                    {
                      "type": "instance",
                      "name": "carte 5",
                      "dep": "ReviewCard",
                      "depProps": {
                        "Auteur": "Prénom N.",
                        "Initiale": "P",
                        "Date": "il y a 6 mois",
                        "Témoignage": "Un témoignage neutre, exemple générique de contenu.",
                        "Avatar initiale": true,
                        "Avatar photo": false,
                        "URL photo": "",
                        "Alt photo": "",
                        "Vérifié": true,
                        "Tronqué": false
                      }
                    }
                  ]
                },
                {
                  "type": "frame",
                  "name": "flecheDroite",
                  "layout": {
                    "mode": "HORIZONTAL",
                    "primary": "CENTER",
                    "counter": "CENTER"
                  },
                  "lits": {
                    "width": 0,
                    "minWidth": 0
                  },
                  "children": [
                    {
                      "type": "frame",
                      "name": "pastilleDroite",
                      "layout": {
                        "mode": "HORIZONTAL",
                        "primary": "CENTER",
                        "counter": "CENTER"
                      },
                      "fill": "color/blanc",
                      "stroke": "color/bleu-clair",
                      "lits": {
                        "width": 30,
                        "height": 30,
                        "minWidth": 30,
                        "radius": 15,
                        "strokeWeight": 1
                      },
                      "children": [
                        {
                          "type": "svg",
                          "name": "iconeDroite",
                          "svg": "<svg width=\"14\" height=\"14\" viewBox=\"0 0 32 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M11.293 7.29302C11.6835 6.90249 12.3165 6.90249 12.707 7.29302L20.707 15.293C21.0975 15.6835 21.0975 16.3166 20.707 16.7071L12.707 24.7071C12.3165 25.0976 11.6835 25.0976 11.293 24.7071C10.9024 24.3166 10.9024 23.6835 11.293 23.293L18.5859 16L11.293 8.70708C10.9024 8.31655 10.9024 7.68354 11.293 7.29302Z\" fill=\"#000000\"/>\n</svg>",
                          "iconSize": 14
                        }
                      ]
                    }
                  ],
                  "visibleProp": "Contrôles",
                  "visibleDefault": true
                }
              ]
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "Input",
    "contractId": "ds.input",
    "anchorKey": "376ed2e3d748a430b28e763035ba5c62bdc9b383",
    "description": "Input — generated from contract ds.input v1.0.0",
    "isSet": false,
    "boolProps": [],
    "textProps": [],
    "fontStyles": [
      "Medium",
      "Regular"
    ],
    "variants": [
      {
        "name": "Input",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Input",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "MIN",
            "counter": "CENTER"
          },
          "fill": "color/blanc",
          "stroke": "color/bleu-gris",
          "lits": {
            "paddingTop": 12,
            "paddingBottom": 12,
            "paddingLeft": 12,
            "paddingRight": 12,
            "strokeWeight": 1,
            "radius": 0
          },
          "children": [
            {
              "type": "text",
              "name": "texteDeSaisie",
              "characters": "Texte de saisie",
              "fontSize": 14,
              "fontStyle": "Regular",
              "textFill": "color/noir",
              "lineHeight": 24,
              "fontFamily": "Montserrat",
              "contentProp": "Valeur"
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "Select",
    "contractId": "ds.select",
    "anchorKey": "3063f8a5ed587927ede2ae021433c705656acff5",
    "description": "Select — generated from contract ds.select v1.0.0",
    "isSet": false,
    "boolProps": [],
    "textProps": [],
    "fontStyles": [
      "Medium",
      "Regular"
    ],
    "variants": [
      {
        "name": "Select",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Select",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "SPACE_BETWEEN",
            "counter": "CENTER"
          },
          "fill": "color/blanc",
          "stroke": "color/bleu-gris",
          "lits": {
            "paddingTop": 12,
            "paddingBottom": 12,
            "paddingLeft": 12,
            "paddingRight": 12,
            "strokeWeight": 1,
            "radius": 0
          },
          "children": [
            {
              "type": "text",
              "name": "valeur",
              "characters": "Texte de saisie",
              "fontSize": 14,
              "fontStyle": "Regular",
              "textFill": "color/noir",
              "lineHeight": 24,
              "fontFamily": "Montserrat",
              "contentProp": "Valeur"
            },
            {
              "type": "svg",
              "name": "chevron",
              "svg": "<svg width=\"24\" height=\"24\" viewBox=\"0 0 32 32\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\n<path d=\"M7.29302 12.7071C6.90249 12.3166 6.90249 11.6836 7.29302 11.293C7.68354 10.9025 8.31655 10.9025 8.70708 11.293L16 18.586L23.293 11.293C23.6835 10.9025 24.3166 10.9025 24.7071 11.293C25.0976 11.6836 25.0976 12.3166 24.7071 12.7071L16.7071 20.7071C16.3166 21.0976 15.6835 21.0976 15.293 20.7071L7.29302 12.7071Z\" fill=\"#37373B\"/>\n</svg>",
              "svgPaintVar": "color/noir",
              "iconSize": 24
            }
          ]
        }
      }
    ],
    "colW": 380
  },
  {
    "setName": "Textarea",
    "contractId": "ds.textarea",
    "anchorKey": "cdeef5ac88e94d53b8fe1cefcad341d5c7df79bd",
    "description": "Textarea — generated from contract ds.textarea v1.0.0",
    "isSet": false,
    "boolProps": [],
    "textProps": [],
    "fontStyles": [
      "Medium",
      "Regular"
    ],
    "variants": [
      {
        "name": "Textarea",
        "row": 0,
        "col": 0,
        "spec": {
          "type": "root",
          "name": "Textarea",
          "layout": {
            "mode": "HORIZONTAL",
            "primary": "MIN",
            "counter": "MIN"
          },
          "fill": "color/blanc",
          "stroke": "color/bleu-gris",
          "lits": {
            "paddingTop": 12,
            "paddingBottom": 12,
            "paddingLeft": 12,
            "paddingRight": 12,
            "strokeWeight": 1,
            "radius": 0,
            "height": 128
          },
          "children": [
            {
              "type": "text",
              "name": "texteDeSaisie",
              "characters": "Texte de saisie",
              "fontSize": 14,
              "fontStyle": "Regular",
              "textFill": "color/noir",
              "lineHeight": 24,
              "fontFamily": "Montserrat",
              "contentProp": "Valeur"
            }
          ]
        }
      }
    ],
    "colW": 380
  }
];
const ROW_H = 240, PAD = 40;

const EXPECTED_FILE_KEY = "d9FYAUcqdcNtsuaMgLefvJ";
if (EXPECTED_FILE_KEY && figma.fileKey && figma.fileKey !== EXPECTED_FILE_KEY) {
  throw new Error('WRONG FILE: expected ' + EXPECTED_FILE_KEY + ', got ' + figma.fileKey);
}

await figma.loadAllPagesAsync();

const allVars = await figma.variables.getLocalVariablesAsync();
const varByName = {};
for (const v of allVars) varByName[v.name] = v;
const need = (name) => {
  const v = varByName[name];
  if (!v) throw new Error('Missing variable: ' + name);
  return v;
};
const boundPaint = (varName, consumer) => {
  // Seed the base with the resolved value when a consumer node is known:
  // Figma keeps rendering a reassigned bound paint's BASE color on
  // pre-existing nodes (fresh nodes normalize at assignment) — without the
  // seed, amended variants render black. The binding itself is unchanged.
  // B-3 finding 2: the resolved ALPHA rides the seed too (paint opacity) —
  // discarding it rendered Badge's rgba(0,0,0,.06) pill as opaque black on
  // amended nodes.
  const v = need(varName);
  let base = { r: 0, g: 0, b: 0 };
  let alpha = 1;
  if (consumer) {
    try {
      const r = v.resolveForConsumer(consumer);
      if (r && r.value && r.value.r !== undefined) {
        base = { r: r.value.r, g: r.value.g, b: r.value.b };
        if (typeof r.value.a === 'number') alpha = r.value.a;
      }
    } catch (e) { /* fall back to black base */ }
  }
  return figma.variables.setBoundVariableForPaint({ type: 'SOLID', color: base, opacity: alpha }, 'color', v);
};

// Named text styles (synced by 01-tokens.js): consumers look up OUR styles
// only — the ds_contracts/textStyleToken marker is identity, a foreign style
// sharing a name is never used. Missing style (tokens script not run yet)
// degrades gracefully: the raw fontName/fontSize already set on the node
// stand until the next amend after the styles exist.
let _textStyleMap = null;
async function ourTextStyle(name) {
  if (!_textStyleMap) {
    _textStyleMap = {};
    for (const s of await figma.getLocalTextStylesAsync()) {
      if (s.getSharedPluginData('ds_contracts', 'textStyleToken')) _textStyleMap[s.name] = s;
    }
  }
  return _textStyleMap[name] || null;
}

const fontStyles = new Set(['Medium']);
for (const C of COMPONENTS) for (const s of C.fontStyles) fontStyles.add(s);
for (const style of fontStyles) {
  await figma.loadFontAsync({ family: 'Inter', style });
}

// State previews (figmaStatePreviews): merge the enum-API cartesian with the
// canvas-only preview overlay; base variants gain an explicit State=Default
// segment so every variant in the set carries the axis (Figma derives
// variant properties from names). Contracts without previews pass through
// untouched — names, hashes, and amend reconciliation are unchanged.
function withStateAxis(C) {
  if (!C.stateVariants || C.stateVariants.length === 0) return C.variants;
  return C.variants.map((v) => {
    const name = v.name.indexOf('=') >= 0 ? v.name + ', State=Default' : 'State=Default';
    return Object.assign({}, v, { name: name, spec: Object.assign({}, v.spec, { name: name }) });
  }).concat(C.stateVariants);
}

function findComponentByName(name) {
  for (const page of figma.root.children) {
    const hit = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === name,
    );
    if (hit) return hit;
  }
  throw new Error('Dependency component not found in file: ' + name + ' (sync it first)');
}

function setInstanceProps(inst, props) {
  const available = Object.keys(inst.componentProperties);
  const resolved = {};
  for (const [wanted, value] of Object.entries(props)) {
    const key = available.find((k) => k === wanted || k.startsWith(wanted + '#'));
    if (key) resolved[key] = value;
  }
  if (Object.keys(resolved).length > 0) inst.setProperties(resolved);
}

let _slotUtil = null;
async function ensureSlotUtility() {
  if (_slotUtil) return _slotUtil;
  for (const page of figma.root.children) {
    const hit = page.findOne((n) => n.type === 'COMPONENT' && n.name === 'Slot');
    if (hit) { _slotUtil = hit; return hit; }
  }
  // Fresh file: create it (found by the 2026-07-06 fresh-file rebuild test —
  // the lookup-only version threw in a blank file).
  await figma.loadFontAsync({ family: 'Inter', style: 'Medium' });
  const util = figma.createComponent();
  util.name = 'Slot';
  util.layoutMode = 'HORIZONTAL';
  util.primaryAxisAlignItems = 'CENTER';
  util.counterAxisAlignItems = 'CENTER';
  util.paddingLeft = util.paddingRight = 12;
  util.paddingTop = util.paddingBottom = 8;
  util.cornerRadius = 4;
  util.fills = [];
  util.strokes = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.dashPattern = [4, 4];
  const t = figma.createText();
  t.fontName = { family: 'Inter', style: 'Medium' };
  t.fontSize = 12;
  t.characters = 'Slot';
  t.fills = [{ type: 'SOLID', color: { r: 0.6, g: 0.62, b: 0.68 } }];
  util.appendChild(t);
  let utilPage = figma.root.children.find((p) => p.name === 'Utilities');
  if (!utilPage) { utilPage = figma.createPage(); utilPage.name = 'Utilities'; }
  utilPage.appendChild(util);
  util.x = 100; util.y = 100;
  _slotUtil = util;
  return util;
}

function applyFrameSpec(node, spec) {
  const l = spec.layout || { mode: 'HORIZONTAL', primary: 'MIN', counter: 'MIN' };
  node.layoutMode = l.mode;
  node.primaryAxisAlignItems = l.primary;
  node.counterAxisAlignItems = l.counter;
  node.primaryAxisSizingMode = 'AUTO';
  node.counterAxisSizingMode = 'AUTO';
  if (node.type === 'FRAME') node.fills = [];
  for (const [field, varName] of Object.entries(spec.bindings || {})) {
    node.setBoundVariable(field, need(varName));
  }
  if (spec.fill) node.fills = [boundPaint(spec.fill, node)];
  if (spec.stroke) {
    node.strokes = [boundPaint(spec.stroke, node)];
    node.strokeAlign = 'INSIDE';
  }
  if (spec.fixedWidth || spec.fixedHeight) {
    const w = spec.fixedWidth ? spec.fixedWidth.px : node.width;
    const h = spec.fixedHeight ? spec.fixedHeight.px : node.height;
    node.resize(w, h);
    const horizontalIsPrimary = l.mode === 'HORIZONTAL';
    if (spec.fixedWidth) {
      if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED';
      else node.counterAxisSizingMode = 'FIXED';
      node.setBoundVariable('width', need(spec.fixedWidth.varName));
    }
    if (spec.fixedHeight) {
      if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED';
      else node.primaryAxisSizingMode = 'FIXED';
      if (spec.fixedHeight.varName) node.setBoundVariable('height', need(spec.fixedHeight.varName));
    }
  }
  if (spec.lits) {
    // v14 literals: no variable to bind — plain values, compile-parsed.
    const li = spec.lits;
    if (li.paddingTop !== undefined) node.paddingTop = li.paddingTop;
    if (li.paddingBottom !== undefined) node.paddingBottom = li.paddingBottom;
    if (li.paddingLeft !== undefined) node.paddingLeft = li.paddingLeft;
    if (li.paddingRight !== undefined) node.paddingRight = li.paddingRight;
    if (li.itemSpacing !== undefined) node.itemSpacing = li.itemSpacing;
    if (li.radius !== undefined) node.cornerRadius = li.radius;
    if (li.strokeWeight !== undefined) node.strokeWeight = li.strokeWeight;
    if (li.minWidth !== undefined) { try { node.minWidth = li.minWidth; } catch (e) { /* needs auto-layout */ } }
    if (li.minHeight !== undefined) { try { node.minHeight = li.minHeight; } catch (e) { /* needs auto-layout */ } }
    // #60 fix 1 (fillClear precedence): a spec-carried fill is NEVER
    // trampled — fillClear only clears when no fill was spec'd. The compile
    // side already drops fillClear when a fill binding exists (applyLiterals);
    // this runtime guard makes the emitted script safe even for hand-fed
    // specs carrying both.
    if (li.fillClear && !spec.fill) node.fills = [];
    else if (li.fillColor) node.fills = [{ type: 'SOLID', color: { r: li.fillColor.r, g: li.fillColor.g, b: li.fillColor.b }, opacity: li.fillColor.a === undefined ? 1 : li.fillColor.a }];
    if (li.radiusCorners) {
      const rc = li.radiusCorners;
      if (rc.tl !== undefined) node.topLeftRadius = rc.tl;
      if (rc.tr !== undefined) node.topRightRadius = rc.tr;
      if (rc.bl !== undefined) node.bottomLeftRadius = rc.bl;
      if (rc.br !== undefined) node.bottomRightRadius = rc.br;
    }
    if (li.strokeSides) {
      const sw = li.strokeSides;
      if (sw.top !== undefined) node.strokeTopWeight = sw.top;
      if (sw.right !== undefined) node.strokeRightWeight = sw.right;
      if (sw.bottom !== undefined) node.strokeBottomWeight = sw.bottom;
      if (sw.left !== undefined) node.strokeLeftWeight = sw.left;
    }
    if (li.width !== undefined || li.height !== undefined) {
      node.resize(li.width !== undefined ? li.width : node.width, li.height !== undefined ? li.height : node.height);
      const horizontalIsPrimary = (spec.layout || { mode: 'HORIZONTAL' }).mode === 'HORIZONTAL';
      if (li.width !== undefined) {
        if (horizontalIsPrimary) node.primaryAxisSizingMode = 'FIXED'; else node.counterAxisSizingMode = 'FIXED';
      }
      if (li.height !== undefined) {
        if (horizontalIsPrimary) node.counterAxisSizingMode = 'FIXED'; else node.primaryAxisSizingMode = 'FIXED';
      }
    }
  }
}

// v7 overlay: out-of-flow edge attachment. Must run AFTER appendChild —
// layoutPositioning ABSOLUTE requires an auto-layout parent.
function applyOverlay(parent, childNode, childSpec) {
  if (!childSpec.overlay) return;
  try {
    childNode.layoutPositioning = 'ABSOLUTE';
    const p = childSpec.overlay.placement;
    childNode.constraints =
      p === 'bottom' ? { horizontal: 'MIN', vertical: 'MAX' } :
      p === 'end' ? { horizontal: 'MAX', vertical: 'MIN' } :
      { horizontal: 'MIN', vertical: 'MIN' };
    if (p === 'top') { childNode.x = 0; childNode.y = -childNode.height; }
    else if (p === 'bottom') { childNode.x = 0; childNode.y = parent.height; }
    else if (p === 'start') { childNode.x = -childNode.width; childNode.y = 0; }
    else { childNode.x = parent.width; childNode.y = 0; }
  } catch (e) { /* parent not auto-layout — leave in flow */ }
}

async function buildNode(spec, registry) {
  let node;
  if (spec.type === 'svg') {
    node = figma.createNodeFromSvg(spec.svg);
    node.fills = [];
    node.clipsContent = false;
    if (spec.iconSize) node.resize(spec.iconSize, spec.iconSize);
    if (spec.svgPaintVar) {
      const glyphPaint = boundPaint(spec.svgPaintVar, node);
      const rebind = (n) => {
        if (Array.isArray(n.fills) && n.fills.length > 0) n.fills = [glyphPaint];
        if (Array.isArray(n.strokes) && n.strokes.length > 0) n.strokes = [glyphPaint];
        if (n.children) for (const c of n.children) rebind(c);
      };
      for (const c of node.children) rebind(c);
    }
  } else if (spec.type === 'text') {
    node = figma.createText();
    node.fontName = { family: 'Inter', style: spec.fontStyle || 'Medium' };
    node.fontSize = spec.fontSize || 16;
    node.characters = spec.characters || '';
    if (typeof spec.lineHeight === 'number') node.lineHeight = { unit: 'PIXELS', value: spec.lineHeight };
    if (spec.fontFamily) {
      try {
        await figma.loadFontAsync({ family: spec.fontFamily, style: spec.fontStyle || 'Medium' });
        node.fontName = { family: spec.fontFamily, style: spec.fontStyle || 'Medium' };
      } catch (e) { /* family unavailable — Inter stands (named limit) */ }
    }
    if (typeof spec.letterSpacing === 'number') node.letterSpacing = { unit: 'PIXELS', value: spec.letterSpacing };
    if (spec.textCase) node.textCase = spec.textCase;
    if (spec.textDecoration) node.textDecoration = spec.textDecoration;
    if (spec.textAlignH) node.textAlignHorizontal = spec.textAlignH;
    if (spec.textTruncation) { try { node.textTruncation = 'ENDING'; } catch (e) { /* older API */ } }
    if (spec.textStyle) {
      // Exact-definition match compiled in: ride the named style. Text
      // styles own typography only — the bound fill paint below coexists.
      const st = await ourTextStyle(spec.textStyle);
      if (st) { try { await node.setTextStyleIdAsync(st.id); } catch (e) { /* raw props stand */ } }
    }
    if (spec.textFill) node.fills = [boundPaint(spec.textFill, node)];
    if (spec.contentProp) {
      registry.texts.push({ prop: spec.contentProp, node, default: spec.characters || '' });
    }
    if (spec.fill || spec.fixedWidth || spec.fixedHeight || spec.bindings) {
      // Styled static text (page chips, dots, thumbs): wrap in a frame so
      // fills/dimensions/radius apply to a container, not the glyphs.
      const wrap = figma.createFrame();
      wrap.layoutMode = 'HORIZONTAL';
      wrap.primaryAxisAlignItems = 'CENTER';
      wrap.counterAxisAlignItems = 'CENTER';
      wrap.primaryAxisSizingMode = 'AUTO';
      wrap.counterAxisSizingMode = 'AUTO';
      wrap.fills = [];
      for (const [field, varName] of Object.entries(spec.bindings || {})) {
        wrap.setBoundVariable(field, need(varName));
      }
      if (spec.fill) wrap.fills = [boundPaint(spec.fill, wrap)];
      if (spec.stroke) { wrap.strokes = [boundPaint(spec.stroke, wrap)]; wrap.strokeAlign = 'INSIDE'; }
      if (spec.characters) wrap.appendChild(node); else node.remove();
      if (spec.fixedWidth || spec.fixedHeight) {
        wrap.resize(spec.fixedWidth ? spec.fixedWidth.px : wrap.width, spec.fixedHeight ? spec.fixedHeight.px : wrap.height);
        if (spec.fixedWidth) { wrap.primaryAxisSizingMode = 'FIXED'; wrap.setBoundVariable('width', need(spec.fixedWidth.varName)); }
        if (spec.fixedHeight) { wrap.counterAxisSizingMode = 'FIXED'; if (spec.fixedHeight.varName) wrap.setBoundVariable('height', need(spec.fixedHeight.varName)); else wrap.resize(wrap.width, spec.fixedHeight.px); }
      }
      wrap.name = spec.name;
      node = wrap;
    }
  } else if (spec.type === 'instance') {
    const target = findComponentByName(spec.dep);
    const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
    node = main.createInstance();
    if (spec.depProps) setInstanceProps(node, spec.depProps);
  } else if (spec.type === 'slot') {
    node = figma.createFrame();
    applyFrameSpec(node, spec);
    const defaults = spec.slotDefault || [];
    if (defaults.length === 0) {
      const util = await ensureSlotUtility();
      const inst = util.createInstance();
      node.appendChild(inst);
      registry.slots.push({ spec, wrapper: node, instance: inst, defaultId: null });
    } else {
      const instances = [];
      for (const item of defaults) {
        const target = findComponentByName(item.dep);
        const main = target.type === 'COMPONENT_SET' ? target.defaultVariant : target;
        const inst = main.createInstance();
        if (item.props) setInstanceProps(inst, item.props);
        node.appendChild(inst);
        if (spec.layout && spec.layout.stretchChildren) {
          try { inst.layoutSizingHorizontal = 'FILL'; } catch (e) { /* fixed-size deps */ }
        }
        instances.push({ inst, main });
      }
      if (defaults.length === 1) {
        registry.slots.push({ spec, wrapper: node, instance: instances[0].inst, defaultId: instances[0].main.id });
      }
    }
  } else {
    node = spec.type === 'root' ? figma.createComponent() : figma.createFrame();
    applyFrameSpec(node, spec);
  }
  node.name = spec.name;
  if (spec.visibleProp) {
    registry.visibles.push({ node, prop: spec.visibleProp, default: spec.visibleDefault === true });
  }
  for (const child of spec.children || []) {
    const childNode = await buildNode(child, registry);
    node.appendChild(childNode);
    applyOverlay(node, childNode, child);
    if (child.pct != null) {
      try {
        childNode.resize(Math.max(1, Math.round(node.width * child.pct)), childNode.height);
        childNode.primaryAxisSizingMode = 'FIXED';
      } catch (e) { /* track not fixed-width */ }
    }
    if (
      child.type === 'frame' && (!child.children || child.children.length === 0) &&
      !child.fixedHeight && !(child.lits && child.lits.height !== undefined) && !child.shape
    ) {
      // #60 fix 4: empty runtime-sized geometry gets DECLARED defaults —
      // height follows the auto-layout parent (FILL), never Figma's 100×100
      // createFrame artifact (Phase B-2 finding 4: ProgressBar indicators
      // overflowed their fixed-height tracks). Width stays the spec'd
      // fraction (meter pct) or the placeholder box, named in the component
      // description.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    if (child.grow && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    } else if (
      spec.layout && spec.layout.stretchChildren &&
      !child.fixedWidth && child.type !== 'instance' &&
      'layoutSizingHorizontal' in childNode
    ) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) { /* HUG-only nodes */ }
    }
  }
  return node;
}


// djb2 over the compiled spec — stored on the set so unchanged components
// skip cheaply and CHANGED ones amend in place.
function specHash(C) {
  let h = 5381; const s = JSON.stringify(C);
  for (let i = 0; i < s.length; i++) h = (((h << 5) + h) + s.charCodeAt(i)) >>> 0;
  return String(h);
}

// IN-PLACE AMEND (2026-07-08, closes the create-only gap): reconcile an
// existing COMPONENT_SET against the compiled spec while preserving what
// instances bind to — the set node + key, each variant COMPONENT node, and
// existing componentProperty IDs. Variant interiors are contract-owned and
// rebuilt from spec (manual interior edits are drift by definition);
// instance-level property overrides survive because property IDs do.
// Destructive changes (extra variants from removed enum values) are
// REPORTED, never deleted — a human retires those.
async function amendSet(set, C) {
  set.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (set.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: set.id, key: set.key };
  }
  const report = { name: C.setName, amended: true, nodeId: set.id, key: set.key,
    addedVariants: [], rebuiltVariants: 0, extraVariants: [], addedProps: [], editedDefaults: [] };
  const defs = set.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;

  for (const w of [
    ...C.boolProps.map((bp) => ({ name: bp.property, type: 'BOOLEAN', def: bp.default })),
    ...(C.textProps || []).map((tp) => ({ name: tp.property, type: 'TEXT', def: tp.default })),
  ]) {
    const k = defKey(w.name);
    if (!k) { newKeys[w.name] = set.addComponentProperty(w.name, w.type, w.def); report.addedProps.push(w.name); }
    else if (defs[k].type === w.type && defs[k].defaultValue !== w.def) {
      set.editComponentProperty(k, { defaultValue: w.def });
      report.editedDefaults.push(w.name);
    }
  }

  // Sets gaining/losing the State preview axis reconcile by RENAME, not
  // duplication: an existing variant whose name matches an expected name
  // minus the ', State=Default' segment IS that variant (instances point at
  // it), so it is renamed in place — every variant node ID is preserved.
  // Main-file finding, 2026-07-08: name-only matching built 12 duplicates
  // and stranded the 12 originals as off-axis extras.
  const EV = withStateAxis(C);
  const expected = new Map(EV.map((v) => [v.name, v]));
  for (const ch of set.children) {
    if (expected.has(ch.name)) continue;
    const gained = ch.name + ', State=Default';
    const lost = ch.name.replace(', State=Default', '');
    if (expected.has(gained) && !set.children.some((o) => o.name === gained)) {
      ch.name = gained;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(gained);
    } else if (lost !== ch.name && expected.has(lost) && !set.children.some((o) => o.name === lost)) {
      ch.name = lost;
      report.renamedVariants = report.renamedVariants || [];
      report.renamedVariants.push(lost);
    } else {
      report.extraVariants.push(ch.name);
    }
  }
  const existingByName = new Map(set.children.map((ch) => [ch.name, ch]));

  for (const v of EV) {
    let comp = existingByName.get(v.name);
    const registry = { texts: [], slots: [], visibles: [] };
    if (!comp) {
      comp = await buildNode(v.spec, registry);
      set.appendChild(comp);
      report.addedVariants.push(v.name);
    } else {
      for (const child of [...comp.children]) child.remove();
      applyFrameSpec(comp, v.spec);
      for (const childSpec of v.spec.children || []) {
        const childNode = await buildNode(childSpec, registry);
        comp.appendChild(childNode);
        applyOverlay(comp, childNode, childSpec);
        if (childSpec.pct != null) {
          try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
        }
        if (
          childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
          !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
        ) {
          // #60 fix 4 (amend path): same empty-child declared default.
          try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
        }
        if (childSpec.grow && 'layoutSizingHorizontal' in childNode) {
          try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        } else if (v.spec.layout && v.spec.layout.stretchChildren && !childSpec.fixedWidth && childSpec.type !== 'instance' && 'layoutSizingHorizontal' in childNode) {
          try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
        }
      }
      report.rebuiltVariants++;
    }
    for (const t of registry.texts) {
      let k = defKey(t.prop);
      if (!k) { k = set.addComponentProperty(t.prop, 'TEXT', t.default); newKeys[t.prop] = k; report.addedProps.push(t.prop); }
      else if (defs[k] && defs[k].defaultValue !== t.default && !report.editedDefaults.includes(t.prop)) {
        set.editComponentProperty(k, { defaultValue: t.default });
        report.editedDefaults.push(t.prop);
      }
      t.node.componentPropertyReferences = { characters: k };
    }
    for (const sl of registry.slots) {
      const util = await ensureSlotUtility();
      let k = defKey(sl.spec.slotProperty);
      if (!k) {
        const preferred = [];
        for (const depName of sl.spec.slotAccepts || []) {
          const target = findComponentByName(depName);
          preferred.push({ type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT', key: target.key });
        }
        k = set.addComponentProperty(sl.spec.slotProperty, 'INSTANCE_SWAP', sl.defaultId || util.id,
          preferred.length > 0 ? { preferredValues: preferred } : undefined);
        newKeys[sl.spec.slotProperty] = k;
        report.addedProps.push(sl.spec.slotProperty);
      }
      sl.instance.componentPropertyReferences = { mainComponent: k };
      if (sl.spec.slotOptional) {
        let vk = defKey('Show ' + sl.spec.slotProperty);
        if (!vk) { vk = set.addComponentProperty('Show ' + sl.spec.slotProperty, 'BOOLEAN', true); newKeys['Show ' + sl.spec.slotProperty] = vk; }
        sl.wrapper.componentPropertyReferences = { visible: vk };
      }
    }
    for (const vis of registry.visibles) {
      const k = defKey(vis.prop);
      if (!k) continue;
      vis.node.componentPropertyReferences = { visible: k };
      vis.node.visible = vis.default;
    }
  }

  // Contract default combo must be the FIRST variant (Figma default = first).
  const first = set.children.find((ch) => ch.name === EV[0].name);
  if (first && set.children[0] !== first) set.insertChild(0, first);

  // Grid re-layout with the create path's math.
  const specByName = new Map(EV.map((sv) => [sv.name, sv]));
  const rowsN = Math.max(...EV.map((vv) => vv.row)) + 1;
  const colsN = Math.max(...EV.map((vv) => vv.col)) + 1;
  const colWs = new Array(colsN).fill(0);
  const rowHs = new Array(rowsN).fill(0);
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    colWs[sp.col] = Math.max(colWs[sp.col], child.width);
    rowHs[sp.row] = Math.max(rowHs[sp.row], child.height);
  }
  for (const child of set.children) {
    const sp = specByName.get(child.name);
    if (!sp) continue;
    let x = PAD, y = PAD;
    for (let i = 0; i < sp.col; i++) x += colWs[i] + PAD;
    for (let i = 0; i < sp.row; i++) y += rowHs[i] + PAD;
    child.x = x; child.y = y;
  }
  // B-3 finding 4: after re-gridding, the SET CONTAINER refits to the
  // children's extent + grid padding (the create path's exact math) —
  // without this, added variants/columns stayed clipped by stale bounds
  // (Banner's Focus column, Button's 220-cell grid, ProgressBar's height).
  // Extra (human-owned) variants may sit beyond the grid; never shrink
  // below their extent.
  {
    let totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    let totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    for (const child of set.children) {
      totalW = Math.max(totalW, child.x + child.width + PAD);
      totalH = Math.max(totalH, child.y + child.height + PAD);
    }
    set.resizeWithoutConstraints(totalW, totalH);
  }
  set.description = C.description;
  set.setSharedPluginData('ds_contracts', 'specHash', hash);
  return report;
}

// #60 fix 3: IN-PLACE AMEND for standalone COMPONENTs (non-set: Badge/Tag
// class) — the same identity-marker update semantics as amendSet: the
// component node (and key) instances bind to is preserved; the interior is
// contract-owned and rebuilt from spec; existing componentProperty IDs
// survive via defKey. Unchanged specs skip on the stored specHash.
async function amendComponent(comp, C) {
  comp.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  const hash = specHash(C);
  if (comp.getSharedPluginData('ds_contracts', 'specHash') === hash) {
    return { name: C.setName, skipped: true, reason: 'unchanged', nodeId: comp.id, key: comp.key };
  }
  const report = { name: C.setName, amended: true, standalone: true, nodeId: comp.id, key: comp.key, addedProps: [], editedDefaults: [] };
  const defs = comp.componentPropertyDefinitions;
  const newKeys = {};
  const defKey = (name) => newKeys[name] ||
    Object.keys(defs).find((k) => k.split('#')[0] === name) || null;
  for (const w of [
    ...C.boolProps.map((bp) => ({ name: bp.property, type: 'BOOLEAN', def: bp.default })),
    ...(C.textProps || []).map((tp) => ({ name: tp.property, type: 'TEXT', def: tp.default })),
  ]) {
    const k = defKey(w.name);
    if (!k) { newKeys[w.name] = comp.addComponentProperty(w.name, w.type, w.def); report.addedProps.push(w.name); }
    else if (defs[k].type === w.type && defs[k].defaultValue !== w.def) {
      comp.editComponentProperty(k, { defaultValue: w.def });
      report.editedDefaults.push(w.name);
    }
  }
  const v = C.variants[0];
  const registry = { texts: [], slots: [], visibles: [] };
  for (const child of [...comp.children]) child.remove();
  applyFrameSpec(comp, v.spec);
  for (const childSpec of v.spec.children || []) {
    const childNode = await buildNode(childSpec, registry);
    comp.appendChild(childNode);
    applyOverlay(comp, childNode, childSpec);
    if (childSpec.pct != null) {
      try { childNode.resize(Math.max(1, Math.round(comp.width * childSpec.pct)), childNode.height); childNode.primaryAxisSizingMode = 'FIXED'; } catch (e) {}
    }
    if (
      childSpec.type === 'frame' && (!childSpec.children || childSpec.children.length === 0) &&
      !childSpec.fixedHeight && !(childSpec.lits && childSpec.lits.height !== undefined) && !childSpec.shape
    ) {
      // #60 fix 4 (standalone amend path): same empty-child declared default.
      try { childNode.layoutSizingVertical = 'FILL'; } catch (e) { /* parent not auto-layout */ }
    }
    if (childSpec.grow && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    } else if (v.spec.layout && v.spec.layout.stretchChildren && !childSpec.fixedWidth && childSpec.type !== 'instance' && 'layoutSizingHorizontal' in childNode) {
      try { childNode.layoutSizingHorizontal = 'FILL'; } catch (e) {}
    }
  }
  for (const t of registry.texts) {
    let k = defKey(t.prop);
    if (!k) { k = comp.addComponentProperty(t.prop, 'TEXT', t.default); newKeys[t.prop] = k; report.addedProps.push(t.prop); }
    else if (defs[k] && defs[k].defaultValue !== t.default && !report.editedDefaults.includes(t.prop)) {
      comp.editComponentProperty(k, { defaultValue: t.default });
      report.editedDefaults.push(t.prop);
    }
    t.node.componentPropertyReferences = { characters: k };
  }
  for (const sl of registry.slots) {
    const util = await ensureSlotUtility();
    let k = defKey(sl.spec.slotProperty);
    if (!k) {
      const preferred = [];
      for (const depName of sl.spec.slotAccepts || []) {
        const target = findComponentByName(depName);
        preferred.push({ type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT', key: target.key });
      }
      k = comp.addComponentProperty(sl.spec.slotProperty, 'INSTANCE_SWAP', sl.defaultId || util.id,
        preferred.length > 0 ? { preferredValues: preferred } : undefined);
      newKeys[sl.spec.slotProperty] = k;
      report.addedProps.push(sl.spec.slotProperty);
    }
    sl.instance.componentPropertyReferences = { mainComponent: k };
    if (sl.spec.slotOptional) {
      let vk = defKey('Show ' + sl.spec.slotProperty);
      if (!vk) { vk = comp.addComponentProperty('Show ' + sl.spec.slotProperty, 'BOOLEAN', true); newKeys['Show ' + sl.spec.slotProperty] = vk; }
      sl.wrapper.componentPropertyReferences = { visible: vk };
    }
  }
  for (const vis of registry.visibles) {
    const k = defKey(vis.prop);
    if (!k) continue;
    vis.node.componentPropertyReferences = { visible: k };
    vis.node.visible = vis.default;
  }
  comp.description = C.description;
  comp.setSharedPluginData('ds_contracts', 'specHash', hash);
  return report;
}

async function syncOne(C) {
  // Identity is the ds_contracts/contractId marker, NOT the set name — in a
  // brownfield file a name can belong to the host system's own component
  // (CBDS pilot: native 72-variant "Badge"). Legacy fallback: sets created
  // before the marker existed carry only specHash under the same namespace.
  let existing = null;
  for (const page of figma.root.children) {
    existing = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') &&
        n.getSharedPluginData('ds_contracts', 'contractId') === C.contractId,
    );
    if (existing) break;
  }
  if (!existing) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName &&
          n.getSharedPluginData('ds_contracts', 'specHash') !== '',
      );
      if (existing) break;
    }
  }
  // An anchored key is ours by definition — the contract records the key the
  // canvas minted. Covers legacy nodes that predate both plugin-data markers
  // (main-file finding, 2026-07-08: 17 standalone components duplicated).
  if (!existing && C.anchorKey) {
    for (const page of figma.root.children) {
      existing = page.findOne(
        (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.key === C.anchorKey,
      );
      if (existing) break;
    }
    if (existing) existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
  }
  if (existing && existing.type === 'COMPONENT_SET' && C.isSet) {
    return await amendSet(existing, C);
  }
  // #60 fix 3: standalone COMPONENTs (Badge/Tag class) amend in place too —
  // the "amend supports variant sets in v1" skip forced delete+recreate and
  // re-minted node ids/keys (Phase B-2 named finding 2).
  if (existing && existing.type === 'COMPONENT' && !C.isSet) {
    return await amendComponent(existing, C);
  }
  if (existing) {
    existing.setSharedPluginData('ds_contracts', 'contractId', C.contractId);
    return { name: C.setName, skipped: true, reason: 'set/standalone shape mismatch (' + existing.type + ' vs isSet=' + C.isSet + ') — a human retires the old node', nodeId: existing.id, key: existing.key };
  }

  // A same-named unmarked set is foreign: leave it alone, disambiguate ours.
  let displayName = C.setName;
  for (const page of figma.root.children) {
    const foreign = page.findOne(
      (n) => (n.type === 'COMPONENT_SET' || n.type === 'COMPONENT') && n.name === C.setName,
    );
    if (foreign) { displayName = C.setName + ' (' + C.contractId + ')'; break; }
  }

  // One page per component (see figma-sync/arrange.js for the file layout).
  let compPage = figma.root.children.find((p) => p.name === displayName);
  if (!compPage) { compPage = figma.createPage(); compPage.name = displayName; }

  const EV = withStateAxis(C);
  const built = [];
  for (const v of EV) {
    const registry = { texts: [], slots: [], visibles: [] };
    const comp = await buildNode(v.spec, registry);
    built.push({ v, comp, registry });
  }
  for (const b of built) {
    for (const t of b.registry.texts) {
      const key = b.comp.addComponentProperty(t.prop, 'TEXT', t.default);
      t.node.componentPropertyReferences = { characters: key };
    }
    for (const s of b.registry.slots) {
      const util = await ensureSlotUtility();
      const preferred = [];
      for (const depName of s.spec.slotAccepts || []) {
        const target = findComponentByName(depName);
        preferred.push({
          type: target.type === 'COMPONENT_SET' ? 'COMPONENT_SET' : 'COMPONENT',
          key: target.key,
        });
      }
      const key = b.comp.addComponentProperty(
        s.spec.slotProperty,
        'INSTANCE_SWAP',
        s.defaultId || util.id,
        preferred.length > 0 ? { preferredValues: preferred } : undefined,
      );
      s.instance.componentPropertyReferences = { mainComponent: key };
      if (s.spec.slotOptional) {
        const vkey = b.comp.addComponentProperty('Show ' + s.spec.slotProperty, 'BOOLEAN', true);
        s.wrapper.componentPropertyReferences = { visible: vkey };
      }
    }
    const boolKeys = {};
    for (const bp of C.boolProps) {
      boolKeys[bp.property] = b.comp.addComponentProperty(bp.property, 'BOOLEAN', bp.default);
    }
    for (const tp of C.textProps || []) {
      b.comp.addComponentProperty(tp.property, 'TEXT', tp.default);
    }
    for (const vis of b.registry.visibles) {
      const key = boolKeys[vis.prop];
      if (!key) continue;
      vis.node.componentPropertyReferences = { visible: key };
      vis.node.visible = vis.default;
    }
  }

  let target;
  if (C.isSet) {
    // combineAsVariants requires the nodes to already be ON the parent page.
    for (const b of built) compPage.appendChild(b.comp);
    target = figma.combineAsVariants(built.map((b) => b.comp), compPage);
    // Tight grid: rows = first axis, columns = second; per-track max sizing.
    const specByName = new Map(EV.map((s) => [s.name, s]));
    const rowsN = Math.max(...EV.map((v) => v.row)) + 1;
    const colsN = Math.max(...EV.map((v) => v.col)) + 1;
    const colWs = new Array(colsN).fill(0);
    const rowHs = new Array(rowsN).fill(0);
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      colWs[spec.col] = Math.max(colWs[spec.col], child.width);
      rowHs[spec.row] = Math.max(rowHs[spec.row], child.height);
    }
    for (const child of target.children) {
      const spec = specByName.get(child.name);
      if (!spec) continue;
      let x = PAD, y = PAD;
      for (let i = 0; i < spec.col; i++) x += colWs[i] + PAD;
      for (let i = 0; i < spec.row; i++) y += rowHs[i] + PAD;
      child.x = x;
      child.y = y;
    }
    const totalW = colWs.reduce((a, b) => a + b, 0) + PAD * (colsN + 1);
    const totalH = rowHs.reduce((a, b) => a + b, 0) + PAD * (rowsN + 1);
    target.resizeWithoutConstraints(totalW, totalH);
  } else {
    target = built[0].comp;
    compPage.appendChild(target);
  }
  target.name = displayName;
  target.description = C.description;
  target.x = 100;
  target.y = 100;
  target.setSharedPluginData('ds_contracts', 'specHash', specHash(C));
  target.setSharedPluginData('ds_contracts', 'contractId', C.contractId);

  return {
    name: C.setName,
    nodeId: target.id,
    key: target.key,
    variants: C.isSet ? target.children.length : 1,
    properties: Object.keys(target.componentPropertyDefinitions || {}),
  };
}

const results = [];
for (const C of COMPONENTS) {
  results.push(await syncOne(C));
}
return { createdNodeIds: results.filter((r) => !r.skipped).map((r) => r.nodeId), results };
