/**
 * The generated-React capture leg of the organism audit (D4).
 *
 * The audit's "generated" leg is evidence only when it observes the component
 * this repository actually ships: a real file under `src/components/**`, its
 * real export, and a pinned hash of the bytes that were rendered.
 *
 * The cheap escape hatch is to render the contract through `core/emit-html`
 * instead.  That string is HTML the audit itself just produced, so comparing it
 * to Figma proves the emitter agrees with the emitter — nothing about the
 * library a consumer installs.  It is refused here rather than downgraded later.
 *
 * Resolution is evidence-based rather than convention-based: the component is
 * found by reading the provenance header the generator writes into every file
 * (`Source of truth: contracts/x.contract.json (ds.x v1.0.0)`).  Guessing a
 * directory name from the contract id would quietly mis-resolve the organisms
 * whose casing is irregular — `SAV`, `FAQ`, `TexteSEO`.
 *
 * Reference: research.md D4; contracts/audit-campaign.interface.md.
 */
import { createHash } from 'node:crypto';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

import type { FactOutcome } from './verdict.js';

/** The only authoritative surface — the generated React library as it ships. */
export const AUTHORITATIVE_SURFACE = 'react-storybook';

export interface GeneratedComponentRef {
  /** Repository-relative path of the generated component. */
  componentFile: string;
  export: string;
  /** SHA-256 over the generated bytes that back the render. */
  bundleSha256: string;
  /** The generated files the hash covers, repository-relative and sorted. */
  hashedFiles: string[];
}

export type GeneratedComponentResolution =
  | { ok: true; ref: GeneratedComponentRef; reasons: [] }
  | { ok: false; reasons: string[] };

/** Marks a file as generator output rather than hand-authored source. */
const GENERATED_MARKER = 'GENERATED FILE';
const COMPONENT_ROOT_SUFFIX = path.join('src', 'components');

/**
 * Resolve the shipping component for a contract id.
 *
 * The capture root is bounded to `src/components`: pointed at the engine, the
 * generated Figma scripts or the repository root, whatever it found there would
 * not be the shipping component, so an out-of-bounds root is refused outright
 * instead of resolving something plausible.
 */
export function resolveGeneratedComponent(input: {
  contractId: string;
  sourceRoot: string;
}): GeneratedComponentResolution {
  const { contractId, sourceRoot } = input;
  const reasons: string[] = [];

  if (typeof contractId !== 'string' || !/^ds\.[a-z0-9][a-z0-9-]*$/.test(contractId)) {
    return { ok: false, reasons: [`contract-id-malformed:${JSON.stringify(contractId)}`] };
  }
  // A relative root cannot be proven to be the checkout's component tree.
  if (typeof sourceRoot !== 'string' || !path.isAbsolute(sourceRoot)) {
    return { ok: false, reasons: [`capture-root-not-absolute:${String(sourceRoot)}`] };
  }
  const root = path.resolve(sourceRoot);
  if (!root.endsWith(COMPONENT_ROOT_SUFFIX)) {
    return {
      ok: false,
      reasons: [`capture-root-outside-src-components:${root}`],
    };
  }
  if (!existsSync(root) || !statSync(root).isDirectory()) {
    return { ok: false, reasons: [`capture-root-missing:${root}`] };
  }
  // `<root>/src/components` -> `<root>`; used to report repository-relative paths.
  const repoRoot = root.slice(0, root.length - COMPONENT_ROOT_SUFFIX.length - 1);

  // Find the component whose generated provenance header cites this contract.
  const provenance = `(${contractId} v`;
  const candidates: string[] = [];
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const componentFile = path.join(root, entry.name, `${entry.name}.tsx`);
    if (!existsSync(componentFile)) continue;
    const source = readFileSync(componentFile, 'utf8');
    if (!source.includes(GENERATED_MARKER)) continue;
    if (!source.includes(provenance)) continue;
    candidates.push(componentFile);
  }

  if (candidates.length === 0) {
    return { ok: false, reasons: [`no-generated-component-for-contract:${contractId}`] };
  }
  if (candidates.length > 1) {
    // Two components claiming one contract is an ambiguity the audit must not
    // resolve by picking one.
    return {
      ok: false,
      reasons: [
        `ambiguous-generated-component:${contractId}:${candidates
          .map((file) => path.relative(repoRoot, file))
          .sort()
          .join('+')}`,
      ],
    };
  }

  const componentFile = candidates[0];
  const source = readFileSync(componentFile, 'utf8');
  const exported = /export const (\w+)\s*=/.exec(source);
  if (exported === null) {
    reasons.push(`generated-component-has-no-export:${path.relative(repoRoot, componentFile)}`);
    return { ok: false, reasons };
  }

  // Hash every generated file that backs the render, in a stable order, so two
  // captures of the same build agree and two different builds cannot claim the
  // same evidence.
  const componentDir = path.dirname(componentFile);
  const hashedAbsolute = readdirSync(componentDir)
    .filter((name) => /\.(tsx|css|ts)$/.test(name) && !name.endsWith('.stories.tsx'))
    .map((name) => path.join(componentDir, name))
    .sort();
  const digest = createHash('sha256');
  for (const file of hashedAbsolute) {
    digest.update(path.relative(repoRoot, file));
    digest.update('\0');
    digest.update(readFileSync(file));
    digest.update('\0');
  }

  return {
    ok: true,
    reasons: [],
    ref: {
      componentFile: path.relative(repoRoot, componentFile),
      export: exported[1],
      bundleSha256: digest.digest('hex'),
      hashedFiles: hashedAbsolute.map((file) => path.relative(repoRoot, file)),
    },
  };
}

export interface SurfaceAssertion {
  ok: boolean;
  /** The outcome this surface forces on the fact; `null` when it forces none. */
  outcome: FactOutcome | null;
  reasons: string[];
}

/**
 * Refuse any surface that is not the shipping React library.
 *
 * `emit-html` is pinned to `not-proven` rather than merely "not authoritative":
 * a fallback that silently downgraded to a softer verdict — or worse, rode an
 * agreeing comparison into a pass — is exactly the failure this refuses.
 */
export function assertReactSurfaceAuthoritative(surface: string): SurfaceAssertion {
  if (surface === AUTHORITATIVE_SURFACE) return { ok: true, outcome: null, reasons: [] };
  if (typeof surface === 'string' && surface.includes('emit-html')) {
    return {
      ok: false,
      outcome: 'not-proven',
      reasons: [
        `surface-fell-back-to-emit-html:${surface}`,
        'emit-html-is-a-diagnostic-not-the-shipping-library',
      ],
    };
  }
  return {
    ok: false,
    outcome: 'not-proven',
    reasons: [`surface-not-authoritative:${JSON.stringify(surface)}`],
  };
}
